/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Business;

/**
 *
 * @author pranjalpatil
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {

    private Business business;

    private JPanel cardPanel;

    public AdminWorkAreaPanel() {

        initComponents();

    }

    public void setContext(Business business, JPanel cardPanel) {
        this.business = business;
        this.cardPanel = cardPanel;
    }

    // ====== [ADDED] overloaded ctor used by MainFrame ======
    /**
     * Creates new form AdminWorkAreaPanel
     */
    public AdminWorkAreaPanel(Business business, JPanel cardPanel) {

        this();

        this.business = business;

        this.cardPanel = cardPanel;

        // optional: show app name on the header if the label exists
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMngPersons = new javax.swing.JButton();
        btnAnalytics = new javax.swing.JButton();
        btnMngAcc = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblWelcomeAdmin = new javax.swing.JLabel();
        btnMngUsers = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setPreferredSize(new java.awt.Dimension(800, 600));

        btnMngPersons.setBackground(new java.awt.Color(204, 255, 255));
        btnMngPersons.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnMngPersons.setForeground(new java.awt.Color(0, 102, 102));
        btnMngPersons.setText("Manage Persons");
        btnMngPersons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMngPersons.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMngPersons.setMinimumSize(new java.awt.Dimension(20, 23));
        btnMngPersons.setPreferredSize(new java.awt.Dimension(240, 30));
        btnMngPersons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngPersonsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnAnalytics.setBackground(new java.awt.Color(204, 255, 255));
        btnAnalytics.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnAnalytics.setForeground(new java.awt.Color(0, 102, 102));
        btnAnalytics.setText("Analytics");
        btnAnalytics.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAnalytics.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAnalytics.setMinimumSize(new java.awt.Dimension(20, 20));
        btnAnalytics.setPreferredSize(new java.awt.Dimension(240, 25));
        btnAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticsActionPerformed(evt);
            }
        });

        btnMngAcc.setBackground(new java.awt.Color(204, 255, 255));
        btnMngAcc.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnMngAcc.setForeground(new java.awt.Color(0, 102, 102));
        btnMngAcc.setText("Manage Students");
        btnMngAcc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMngAcc.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMngAcc.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMngAcc.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMngAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngAccActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(204, 255, 255));
        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 102, 102));
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setMaximumSize(new java.awt.Dimension(145, 40));
        btnLogout.setMinimumSize(new java.awt.Dimension(20, 20));
        btnLogout.setPreferredSize(new java.awt.Dimension(240, 25));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutIdentifyEventsActionPerformed(evt);
            }
        });

        lblWelcomeAdmin.setBackground(new java.awt.Color(0, 255, 255));
        lblWelcomeAdmin.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        lblWelcomeAdmin.setForeground(new java.awt.Color(0, 102, 102));
        lblWelcomeAdmin.setText("Welcome Admin!!");

        btnMngUsers.setBackground(new java.awt.Color(204, 255, 255));
        btnMngUsers.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnMngUsers.setForeground(new java.awt.Color(0, 102, 102));
        btnMngUsers.setText("Manage Users");
        btnMngUsers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMngUsers.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMngUsers.setMinimumSize(new java.awt.Dimension(20, 23));
        btnMngUsers.setPreferredSize(new java.awt.Dimension(240, 30));
        btnMngUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngUsersIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMngPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(btnMngAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMngUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(btnAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(209, 209, 209))
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(lblWelcomeAdmin)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lblWelcomeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMngPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMngAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMngUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnMngPersonsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngPersonsIdentifyResourceAssetsActionPerformed

        ManagePersonsJPanel panel = new ManagePersonsJPanel(business, cardPanel);
        cardPanel.add(panel, "ManagePersons");
        ((java.awt.CardLayout) cardPanel.getLayout()).show(cardPanel, "ManagePersons");
        cardPanel.revalidate();
        cardPanel.repaint();
    }//GEN-LAST:event_btnMngPersonsIdentifyResourceAssetsActionPerformed

    private void btnAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticsActionPerformed
        DashboardPanel panel = new DashboardPanel(business, cardPanel);
        cardPanel.add(panel, "AnalyticsDashboard");
        ((java.awt.CardLayout) cardPanel.getLayout()).show(cardPanel, "AnalyticsDashboard");
        cardPanel.revalidate();
        cardPanel.repaint();
    }//GEN-LAST:event_btnAnalyticsActionPerformed

    private void btnMngAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngAccActionPerformed
        ManageStudentRecordsJPanel panel = new ManageStudentRecordsJPanel(business, cardPanel);
        cardPanel.add(panel, "ManageStudentsRecord");
        ((java.awt.CardLayout) cardPanel.getLayout()).show(cardPanel, "ManageStudentsRecord");
        cardPanel.revalidate();
        cardPanel.repaint();
    }//GEN-LAST:event_btnMngAccActionPerformed

    private void btnLogoutIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutIdentifyEventsActionPerformed
        cardPanel.removeAll();

        javax.swing.JLabel welcomeLabel = new javax.swing.JLabel();
        welcomeLabel.setFont(new java.awt.Font("Dialog", 0, 24));
        welcomeLabel.setForeground(new java.awt.Color(102, 153, 255));
        welcomeLabel.setText("Education Going Digital .... Info 5100");
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cardPanel.add(welcomeLabel, "welcome");
        ((java.awt.CardLayout) cardPanel.getLayout()).show(cardPanel, "welcome");

        cardPanel.revalidate();
        cardPanel.repaint();
    }//GEN-LAST:event_btnLogoutIdentifyEventsActionPerformed

    private void btnMngUsersIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngUsersIdentifyResourceAssetsActionPerformed
        ManageUserAccountsJPanel next = new ManageUserAccountsJPanel(business, cardPanel);
        showCard(new ManageUserAccountsJPanel(business, cardPanel), "ManageUsers");
    }//GEN-LAST:event_btnMngUsersIdentifyResourceAssetsActionPerformed

    private void showCard(javax.swing.JPanel panel, String name) {

        if (cardPanel == null) {

            JOptionPane.showMessageDialog(this,
                    "Card container not set. Make sure MainFrame creates this panel with (business, cardPanel).");

            return;

        }

        if (!(cardPanel.getLayout() instanceof CardLayout)) {

            JOptionPane.showMessageDialog(this,
                    "Parent container must use CardLayout. Please check MainFrame.");

            return;

        }

        cardPanel.add(name, panel);

        ((CardLayout) cardPanel.getLayout()).show(cardPanel, name);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalytics;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMngAcc;
    private javax.swing.JButton btnMngPersons;
    private javax.swing.JButton btnMngUsers;
    private javax.swing.JLabel lblWelcomeAdmin;
    // End of variables declaration//GEN-END:variables

}
