/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.AdminRole;


import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Business;
import UserInterface.WorkArea.AdminRole.ManageStudentRecords;
import UserInterface.WorkArea.AdminRole.ManagePersonsPanel;
import UserInterface.WorkArea.AdminRole.ManageCoursePanel;


/**
 *
 * @author pranjalpatil
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {
    
            // ====== [ADDED] shared app context + card container ======

    private Business business;

    private JPanel cardPanel;



    // ====== [ADDED] keep a no-arg ctor for NetBeans GUI builder ======

    public AdminWorkAreaPanel() {

        initComponents();          // <-- your NetBeans-generated UI (UNCHANGED)

        
    }

        public void setContext(Business business, JPanel cardPanel) {
        this.business = business;
        this.cardPanel = cardPanel;
    }



    // ====== [ADDED] overloaded ctor used by MainFrame ======

    /**
     * Creates new form AdminWorkAreaPanel
     */
    public AdminWorkAreaPanel(Business business, JPanel cardPanel) {
        
          this();                    // calls initComponents() + safePostInit()

        this.business = business;

        this.cardPanel = cardPanel;



        // optional: show app name on the header if the label exists


    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMngPersons = new javax.swing.JButton();
        btnMngCourses = new javax.swing.JButton();
        btnMngAcc = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblWelcomeAdmin = new javax.swing.JLabel();
        btnMngUsers = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setPreferredSize(new java.awt.Dimension(800, 600));

        btnMngPersons.setBackground(new java.awt.Color(204, 255, 255));
        btnMngPersons.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnMngPersons.setForeground(new java.awt.Color(0, 102, 102));
        btnMngPersons.setText("Manage Persons");
        btnMngPersons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMngPersons.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMngPersons.setMinimumSize(new java.awt.Dimension(20, 23));
        btnMngPersons.setPreferredSize(new java.awt.Dimension(240, 30));
        btnMngPersons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngPersonsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnMngCourses.setBackground(new java.awt.Color(204, 255, 255));
        btnMngCourses.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnMngCourses.setForeground(new java.awt.Color(0, 102, 102));
        btnMngCourses.setText("Manage Courses");
        btnMngCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMngCourses.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMngCourses.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMngCourses.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMngCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngCoursesActionPerformed(evt);
            }
        });

        btnMngAcc.setBackground(new java.awt.Color(204, 255, 255));
        btnMngAcc.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnMngAcc.setForeground(new java.awt.Color(0, 102, 102));
        btnMngAcc.setText("Manage Students");
        btnMngAcc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMngAcc.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMngAcc.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMngAcc.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMngAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngAccActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(204, 255, 255));
        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 102, 102));
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setMaximumSize(new java.awt.Dimension(145, 40));
        btnLogout.setMinimumSize(new java.awt.Dimension(20, 20));
        btnLogout.setPreferredSize(new java.awt.Dimension(240, 25));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutIdentifyEventsActionPerformed(evt);
            }
        });

        lblWelcomeAdmin.setBackground(new java.awt.Color(0, 255, 255));
        lblWelcomeAdmin.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        lblWelcomeAdmin.setForeground(new java.awt.Color(0, 102, 102));
        lblWelcomeAdmin.setText("Welcome Admin!!");

        btnMngUsers.setBackground(new java.awt.Color(204, 255, 255));
        btnMngUsers.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnMngUsers.setForeground(new java.awt.Color(0, 102, 102));
        btnMngUsers.setText("Manage Users");
        btnMngUsers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMngUsers.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMngUsers.setMinimumSize(new java.awt.Dimension(20, 23));
        btnMngUsers.setPreferredSize(new java.awt.Dimension(240, 30));
        btnMngUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngUsersIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMngPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(btnMngAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMngUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(btnMngCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(209, 209, 209))
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(lblWelcomeAdmin)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lblWelcomeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMngPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMngAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMngUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMngCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

     

    
    private void btnMngPersonsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngPersonsIdentifyResourceAssetsActionPerformed
        
    ManagePersonsPanel next = new ManagePersonsPanel(business, cardPanel);
        
        showCard(new ManagePersonsPanel(business, cardPanel), "ManagePersons");
    }//GEN-LAST:event_btnMngPersonsIdentifyResourceAssetsActionPerformed

    private void btnMngCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngCoursesActionPerformed

        ManageCoursePanel next = new ManageCoursePanel(business, cardPanel);
        showCard(new ManageCoursePanel(business, cardPanel), "ManageCourses");
    }//GEN-LAST:event_btnMngCoursesActionPerformed

    private void btnMngAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngAccActionPerformed

            ManageStudentRecords next = new ManageStudentRecords(business, cardPanel);
        showCard(new ManageStudentRecords(business, cardPanel), "ManageStudentsRecord");

 

    }//GEN-LAST:event_btnMngAccActionPerformed

    private void btnLogoutIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutIdentifyEventsActionPerformed
             JOptionPane.showMessageDialog(this,

            "Logged out successfully!");

    
    }//GEN-LAST:event_btnLogoutIdentifyEventsActionPerformed

    private void btnMngUsersIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngUsersIdentifyResourceAssetsActionPerformed
    ManageUserAccountsJPanel next = new ManageUserAccountsJPanel(business, cardPanel);
        showCard(new ManageUserAccountsJPanel(business, cardPanel), "ManageUsers");
    }//GEN-LAST:event_btnMngUsersIdentifyResourceAssetsActionPerformed

    
     private void showCard(javax.swing.JPanel panel, String name) {

        if (cardPanel == null) {

            JOptionPane.showMessageDialog(this,

                "Card container not set. Make sure MainFrame creates this panel with (business, cardPanel).");

            return;

        }

        if (!(cardPanel.getLayout() instanceof CardLayout)) {

            JOptionPane.showMessageDialog(this,

                "Parent container must use CardLayout. Please check MainFrame.");

            return;

        }

        cardPanel.add(name, panel);

        ((CardLayout) cardPanel.getLayout()).show(cardPanel, name);

    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMngAcc;
    private javax.swing.JButton btnMngCourses;
    private javax.swing.JButton btnMngPersons;
    private javax.swing.JButton btnMngUsers;
    private javax.swing.JLabel lblWelcomeAdmin;
    // End of variables declaration//GEN-END:variables

}
