/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.EmployeeProfile;
import Business.Profiles.FacultyProfile;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import java.awt.Color;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pranjalpatil
 */
public class ManagePersonsJPanel extends javax.swing.JPanel {

    private Business business;
    private JPanel cardSequencePanel;
    private Person selectedPerson;
    private ArrayList<Person> displayedPersons;

    public ManagePersonsJPanel(Business business, JPanel cardSequencePanel) {
        this.business = business;
        this.cardSequencePanel = cardSequencePanel;
        this.displayedPersons = new ArrayList<>();

        initComponents();

        setupUI();
        loadAllPersons();
    }

    private void setupUI() {
        comboType.removeAllItems();
        comboType.addItem("Student");
        comboType.addItem("Faculty");
        comboType.addItem("Admin");

        fieldID.setEditable(false);
        fieldID.setBackground(new Color(220, 220, 220));
        fieldID.setText("Auto-generated");

        clearForm();
    }

    private void loadAllPersons() {
        displayedPersons = business.getPersonDirectory().getPersonList();
        populateTable(displayedPersons);
    }

    private void populateTable(ArrayList<Person> persons) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Person person : persons) {
            String type = getPersonType(person);
            String extra = getPersonExtra(person);

            Object[] row = new Object[5];
            row[0] = person.getPersonId();
            row[1] = person.getFullName();
            row[2] = person.getEmail();
            row[3] = type;
            row[4] = extra;

            model.addRow(row);
        }

        jTable1.setDefaultEditor(Object.class, null);

        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                onPersonSelected();
            }
        });
    }

    private String getPersonType(Person person) {
        String personId = person.getPersonId();

        if (business.getStudentDirectory().findStudent(personId) != null) {
            return "Student";
        } else if (business.getFacultyDirectory().findFacultyByPersonId(personId) != null) {
            return "Faculty";
        } else if (business.getEmployeeDirectory().findEmployee(personId) != null) {
            return "Admin";
        } else {
            return "Person";
        }
    }

    private String getPersonExtra(Person person) {
        String personId = person.getPersonId();

        StudentProfile student = business.getStudentDirectory().findStudent(personId);
        if (student != null) {
            return "Credits: " + student.getTranscript().getTotalCredits();
        }

        FacultyProfile faculty = business.getFacultyDirectory().findFacultyByPersonId(personId);
        if (faculty != null) {
            return "Courses: " + faculty.getOfferings().size();
        }

        return "N/A";
    }

    private void onPersonSelected() {
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0) {
            clearForm();
            return;
        }

        selectedPerson = displayedPersons.get(selectedRow);
        loadPersonIntoForm(selectedPerson);
    }

    private void loadPersonIntoForm(Person person) {
        fieldID.setText(person.getPersonId());
        fieldID1.setText(person.getFullName());
        fieldID2.setText(person.getEmail());
        fieldID5.setText(person.getDepartment() != null ? person.getDepartment() : "");

        String type = getPersonType(person);
        comboType.setSelectedItem(type);
    }

    private void clearForm() {
        fieldID.setText("Auto-generated");
        fieldID1.setText("");
        fieldID2.setText("");
        fieldID5.setText("");
        comboType.setSelectedIndex(0);
        selectedPerson = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblPersonMgm = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        lblPersonDetails = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblMajor = new javax.swing.JLabel();
        fieldID = new javax.swing.JTextField();
        fieldID1 = new javax.swing.JTextField();
        fieldID2 = new javax.swing.JTextField();
        comboType = new javax.swing.JComboBox<>();
        fieldID5 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        fieldSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        lblPersonMgm.setBackground(new java.awt.Color(204, 255, 255));
        lblPersonMgm.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPersonMgm.setForeground(new java.awt.Color(255, 255, 255));
        lblPersonMgm.setText("Persons Management");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblPersonMgm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(131, 131, 131))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonMgm)
                    .addComponent(btnBack))
                .addGap(17, 17, 17))
        );

        jSplitPane2.setDividerLocation(230);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        lblPersonDetails.setBackground(new java.awt.Color(255, 255, 255));
        lblPersonDetails.setFont(new java.awt.Font("Lava Devanagari", 1, 18)); // NOI18N
        lblPersonDetails.setForeground(new java.awt.Color(0, 153, 153));
        lblPersonDetails.setText("Person Details");

        lblID.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 102, 102));
        lblID.setText("ID");

        lblName.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 102, 102));
        lblName.setText("Name");

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 102, 102));
        lblEmail.setText("Email");

        lblType.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblType.setForeground(new java.awt.Color(0, 102, 102));
        lblType.setText("Type");

        lblMajor.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblMajor.setForeground(new java.awt.Color(0, 102, 102));
        lblMajor.setText("Major");

        fieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIDActionPerformed(evt);
            }
        });

        fieldID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldID1ActionPerformed(evt);
            }
        });

        fieldID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldID2ActionPerformed(evt);
            }
        });

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Faculty" }));
        comboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTypeActionPerformed(evt);
            }
        });

        fieldID5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldID5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblPersonDetails))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMajor, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldID)
                            .addComponent(fieldID1)
                            .addComponent(fieldID2)
                            .addComponent(comboType, 0, 146, Short.MAX_VALUE)
                            .addComponent(fieldID5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblPersonDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblType))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldID5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMajor))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel6);

        jPanel7.setBackground(new java.awt.Color(102, 255, 255));

        fieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Type", "Extra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        jSplitPane2.setRightComponent(jPanel7);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate)
                    .addComponent(btnAdd))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminWorkAreaPanel dashboard = new AdminWorkAreaPanel(business, cardSequencePanel);
        cardSequencePanel.add(dashboard, "AdminDashboard");
        ((java.awt.CardLayout) cardSequencePanel.getLayout()).show(cardSequencePanel, "AdminDashboard");
        cardSequencePanel.revalidate();
        cardSequencePanel.repaint();
    }//GEN-LAST:event_btnBackActionPerformed

    private void fieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIDActionPerformed

    private void fieldID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldID1ActionPerformed

    private void fieldID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldID2ActionPerformed

    private void comboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTypeActionPerformed

    private void fieldID5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldID5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldID5ActionPerformed

    private void fieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String name = fieldID1.getText().trim();
        String email = fieldID2.getText().trim();
        String type = (String) comboType.getSelectedItem();
        String major = fieldID5.getText().trim();

        if (name.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Name and Email are required fields",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a valid email address",
                    "Invalid Email",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (business.checkDuplicateEmail(email)) {
            JOptionPane.showMessageDialog(this,
                    "Email already exists in the system.\n"
                    + "Please use a different email address.",
                    "Duplicate Email",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] nameParts = name.split(" ", 2);
        String firstName = nameParts[0];
        String lastName = nameParts.length > 1 ? nameParts[1] : "";

        String newId = business.generateUniquePersonId();

        int response = JOptionPane.showConfirmDialog(this,
                "Register new person?\n\n"
                + "ID: " + newId + "\n"
                + "Name: " + name + "\n"
                + "Email: " + email + "\n"
                + "Type: " + type + "\n"
                + "Department: " + (major.isEmpty() ? "N/A" : major),
                "Confirm Registration",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            Person newPerson = business.getPersonDirectory().newPerson(
                    newId, firstName, lastName, email, ""
            );
            newPerson.setDepartment(major.isEmpty() ? null : major);

            String username = firstName.toLowerCase();
            String password = "password";

            switch (type) {
                case "Student":
                    StudentProfile studentProfile = business.getStudentDirectory().newStudentProfile(newPerson);
                    business.getUserAccountDirectory().newUserAccount(studentProfile, username, password);
                    break;

                case "Faculty":
                    FacultyProfile facultyProfile = business.getFacultyDirectory().newFacultyProfile(newPerson);
                    facultyProfile.setDepartment(major);
                    business.getUserAccountDirectory().newUserAccount(facultyProfile, username, password);
                    break;

                case "Admin":
                    EmployeeProfile employeeProfile = business.getEmployeeDirectory().newEmployeeProfile(newPerson);
                    business.getUserAccountDirectory().newUserAccount(employeeProfile, username, password);
                    break;
            }

            JOptionPane.showMessageDialog(this,
                    "Person registered successfully!\n\n"
                    + "ID: " + newId + "\n"
                    + "Username: " + username + "\n"
                    + "Password: " + password + "\n\n"
                    + "Please share these credentials with the user.",
                    "Registration Successful",
                    JOptionPane.INFORMATION_MESSAGE);

            clearForm();
            loadAllPersons();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedPerson == null) {
            JOptionPane.showMessageDialog(this,
                    "Please select a person from the table to update",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String name = fieldID1.getText().trim();
        String email = fieldID2.getText().trim();
        String department = fieldID5.getText().trim();

        if (name.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Name and Email cannot be empty",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a valid email address",
                    "Invalid Email",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!email.equals(selectedPerson.getEmail()) && business.checkDuplicateEmail(email)) {
            JOptionPane.showMessageDialog(this,
                    "Email already exists in the system",
                    "Duplicate Email",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        int response = JOptionPane.showConfirmDialog(this,
                "Update person information?\n\n"
                + "ID: " + selectedPerson.getPersonId() + "\n"
                + "New Name: " + name + "\n"
                + "New Email: " + email + "\n"
                + "New Department: " + (department.isEmpty() ? "N/A" : department),
                "Confirm Update",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            String[] nameParts = name.split(" ", 2);
            selectedPerson.setFirstName(nameParts[0]);
            selectedPerson.setLastName(nameParts.length > 1 ? nameParts[1] : "");
            selectedPerson.setEmail(email);
            selectedPerson.setDepartment(department.isEmpty() ? null : department);

            String personType = getPersonType(selectedPerson);
            if (personType.equals("Faculty")) {
                FacultyProfile fp = business.getFacultyDirectory().findFacultyByPersonId(selectedPerson.getPersonId());
                if (fp != null) {
                    fp.setDepartment(department);
                }
            }

            JOptionPane.showMessageDialog(this,
                    "Person updated successfully!",
                    "Update Successful",
                    JOptionPane.INFORMATION_MESSAGE);

            loadAllPersons();
            clearForm();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedPerson == null) {
            JOptionPane.showMessageDialog(this,
                    "Please select a person from the table to delete",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String personType = getPersonType(selectedPerson);
        String personId = selectedPerson.getPersonId();

        int response = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this person?\n\n"
                + "ID: " + personId + "\n"
                + "Name: " + selectedPerson.getFullName() + "\n"
                + "Type: " + personType + "\n\n"
                + "This action cannot be undone!\n"
                + "This will remove the person and their user account.",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            switch (personType) {
                case "Student":
                    business.getStudentDirectory().removeStudent(personId);
                    break;
                case "Faculty":
                    FacultyProfile fp = business.getFacultyDirectory().findFacultyByPersonId(personId);
                    if (fp != null) {
                        business.getFacultyDirectory().removeFaculty(fp);
                    }
                    break;
                case "Admin":
                    EmployeeProfile ep = business.getEmployeeDirectory().findEmployee(personId);
                    if (ep != null) {
                        business.getEmployeeDirectory().removeEmployee(ep);
                    }
                    break;
            }

            UserAccount ua = business.getUserAccountDirectory().findUserAccount(personId);
            if (ua != null) {
                business.getUserAccountDirectory().removeUserAccount(personId);
            }

            business.getPersonDirectory().removePerson(personId);

            JOptionPane.showMessageDialog(this,
                    "Person deleted successfully!",
                    "Delete Successful",
                    JOptionPane.INFORMATION_MESSAGE);

            clearForm();
            loadAllPersons();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
        jTable1.clearSelection();
        fieldSearch.setText("");

        JOptionPane.showMessageDialog(this,
                "Form cleared",
                "Clear",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchTerm = fieldSearch.getText().trim();

        if (searchTerm.isEmpty()) {
            loadAllPersons();
            JOptionPane.showMessageDialog(this,
                    "Showing all persons",
                    "Search Reset",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        ArrayList<Person> searchResults = new ArrayList<>();
        String searchLower = searchTerm.toLowerCase();

        for (Person person : business.getPersonDirectory().getPersonList()) {
            boolean match = false;

            if (person.getPersonId().toLowerCase().contains(searchLower)) {
                match = true;
            }

            if (person.getFullName().toLowerCase().contains(searchLower)) {
                match = true;
            }

            if (person.getEmail() != null && person.getEmail().toLowerCase().contains(searchLower)) {
                match = true;
            }

            if (person.getDepartment() != null && person.getDepartment().toLowerCase().contains(searchLower)) {
                match = true;
            }

            if (match) {
                searchResults.add(person);
            }
        }

        displayedPersons = searchResults;
        populateTable(searchResults);

        if (searchResults.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No persons found matching '" + searchTerm + "'",
                    "No Results",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Found " + searchResults.size() + " person(s)",
                    "Search Results",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private boolean isValidEmail(String email) {
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        Pattern pattern = Pattern.compile(emailRegex);
        return pattern.matcher(email).matches();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldID1;
    private javax.swing.JTextField fieldID2;
    private javax.swing.JTextField fieldID5;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMajor;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPersonDetails;
    private javax.swing.JLabel lblPersonMgm;
    private javax.swing.JLabel lblType;
    // End of variables declaration//GEN-END:variables
}
