/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Course.Course;
import Business.Course.CourseOffering;
import Business.Course.Enrollment;
import Business.Profiles.CourseDirectory;
import Business.Profiles.StudentProfile;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chinm
 */
public class CourseRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseRegistrationJPanel
     */
    private Business business;
    private StudentProfile studentProfile;
    private JPanel cardSequencePanel;
    private ArrayList<CourseOffering> displayedCourses;

    public CourseRegistrationJPanel(Business business, StudentProfile studentProfile, JPanel cardSequencePanel) {
        this.business = business;
        this.studentProfile = studentProfile;
        this.cardSequencePanel = cardSequencePanel;
        this.displayedCourses = new ArrayList<>();

        initComponents();
        initializeSearchFilter();
        loadAllCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEnroll = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        cmbFilter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        fieldSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(215, 204, 200));

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CourseID", "Title", "Description", "Schedule", "Capacity", "Faculty", "EnrollmentOpen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourses);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Register for Courses");

        btnEnroll.setText("Enroll ");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course ID", "Course Name", "Faculty Name" }));

        jLabel2.setText("Search By");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(402, 402, 402)
                            .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnback))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        StudentWorkAreaJPanel dashboard = new StudentWorkAreaJPanel(business, studentProfile, cardSequencePanel);
        cardSequencePanel.add(dashboard, "StudentDashboard");
        ((java.awt.CardLayout) cardSequencePanel.getLayout()).show(cardSequencePanel, "StudentDashboard");
        cardSequencePanel.revalidate();
        cardSequencePanel.repaint();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        int selectedRow = tblCourses.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a course to enroll in",
                    "No Course Selected",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        CourseOffering selectedOffering = displayedCourses.get(selectedRow);
        Course course = selectedOffering.getCourse();

        if (hasAlreadyTakenCourse(course.getCourseId())) {
            JOptionPane.showMessageDialog(this,
                    "You have already completed " + course.getCourseId() + ".\n"
                    + "Students cannot retake courses they have already passed.",
                    "Course Already Taken",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!selectedOffering.isEnrollmentOpen()) {
            JOptionPane.showMessageDialog(this,
                    "Enrollment is currently closed for " + course.getCourseId(),
                    "Enrollment Closed",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (selectedOffering.isFull()) {
            JOptionPane.showMessageDialog(this,
                    course.getCourseId() + " is full.\n"
                    + "Capacity: " + selectedOffering.getCapacity() + "\n"
                    + "Enrolled: " + selectedOffering.getActiveEnrollmentCount(),
                    "Course Full",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (isAlreadyEnrolled(selectedOffering)) {
            JOptionPane.showMessageDialog(this,
                    "You are already enrolled in " + course.getCourseId(),
                    "Already Enrolled",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String semester = selectedOffering.getSemester();
        int currentCourseCount = getCurrentSemesterCourseCount(semester);

        if (currentCourseCount >= 2) {
            JOptionPane.showMessageDialog(this,
                    "Cannot enroll: Course limit exceeded!\n\n"
                    + "You are already enrolled in " + currentCourseCount + " courses for " + semester + "\n"
                    + "Maximum allowed: 2 courses per semester (8 credit hours)",
                    "Course Limit Exceeded",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        int currentCredits = studentProfile.getCurrentTermCredits(semester);
        int courseCredits = course.getCreditHours();

        if (currentCredits + courseCredits > 8) {
            JOptionPane.showMessageDialog(this,
                    "Cannot enroll: Credit hour limit exceeded!\n\n"
                    + "Current credits for " + semester + ": " + currentCredits + "\n"
                    + "Course credits: " + courseCredits + "\n"
                    + "Total would be: " + (currentCredits + courseCredits) + "\n"
                    + "Maximum allowed: 8 credits per semester",
                    "Credit Limit Exceeded",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        int response = JOptionPane.showConfirmDialog(this,
                "Enroll in " + course.getCourseId() + " - " + course.getCourseName() + "?\n\n"
                + "Credits: " + courseCredits + "\n"
                + "Semester: " + semester + "\n"
                + "Faculty: " + selectedOffering.getFaculty().getPerson().getFullName() + "\n"
                + "Tuition: $" + (courseCredits * 1000) + "\n\n"
                + "Your total courses for " + semester + " will be: "
                + (currentCourseCount + 1) + "/2\n"
                + "Your total credits for " + semester + " will be: "
                + (currentCredits + courseCredits) + "/8",
                "Confirm Enrollment",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            Enrollment enrollment = new Enrollment(studentProfile, selectedOffering);

            boolean success = selectedOffering.enrollStudent(enrollment);

            if (success) {
                studentProfile.addEnrollment(enrollment);

                System.out.println("===== ENROLLMENT DEBUG =====");
                System.out.println("Student: " + studentProfile.getPerson().getFullName());
                System.out.println("Course: " + course.getCourseId());
                System.out.println("Semester: " + selectedOffering.getSemester());
                System.out.println("Total enrollments for student: " + studentProfile.getEnrollments().size());
                System.out.println("Fall 2025 enrollments: " + getCurrentSemesterCourseCount("Fall 2025"));

                for (Enrollment e : studentProfile.getEnrollments()) {
                    System.out.println("  - " + e.getOffering().getCourse().getCourseId()
                            + " (" + e.getOffering().getSemester() + ") - Status: " + e.getStatus());
                }
                System.out.println("============================");

                int newEnrolled = selectedOffering.getActiveEnrollmentCount();
                int capacity = selectedOffering.getCapacity();

                JOptionPane.showMessageDialog(this,
                        "Successfully enrolled in " + course.getCourseId() + "!\n\n"
                        + "Tuition billed: $" + (courseCredits * 1000) + "\n"
                        + "Courses for " + semester + ": "
                        + getCurrentSemesterCourseCount(semester) + "/2\n"
                        + "Credits for " + semester + ": "
                        + studentProfile.getCurrentTermCredits(semester) + "/8\n\n"
                        + "Course Capacity: " + newEnrolled + "/" + capacity,
                        "Enrollment Successful",
                        JOptionPane.INFORMATION_MESSAGE);

                populateCoursesTable(displayedCourses);
            }
        }
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchBy = (String) cmbFilter.getSelectedItem();
        String searchTerm = fieldSearch.getText().trim();

        if (searchTerm.isEmpty()) {
            loadAllCourses();
            return;
        }
        ArrayList<CourseOffering> searchResults = new ArrayList<>();

        switch (searchBy) {
            case "Course ID":
                searchResults = business.getCourseDirectory().searchByCourseId(searchTerm);
                break;

            case "Faculty":
                searchResults = searchByFacultyName(searchTerm);
                break;

            case "Semester":
                searchResults = business.getCourseDirectory().searchBySemester(searchTerm);
                break;

            default:
                searchResults = business.getCourseDirectory().getOfferings();
                break;
        }

        displayedCourses = searchResults;

        populateCoursesTable(searchResults);

        if (searchResults.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No courses found matching '" + searchTerm + "'",
                    "No Results",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void populateTable(ArrayList<CourseOffering> offerings, Business b) {
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
        model.setRowCount(0);

        CourseDirectory cd = b.getCourseDirectory();

        for (CourseOffering co : cd.getOfferings()) {
            model.addRow(new Object[]{
                co.getCourse().getCourseId(),
                co.getCourse().getCourseName(),
                co.getFaculty().getPerson().getPersonId(),
                co.getCourse().getCreditHours(),
                co.getCapacity(),
                co.getFaculty(),
                co.isEnrollmentOpen() ? "Open" : "Closed"
            });
        }
    }

    private ArrayList<CourseOffering> searchByFacultyName(String name) {
        ArrayList<CourseOffering> results = new ArrayList<>();
        String searchLower = name.toLowerCase();

        for (CourseOffering offering : business.getCourseDirectory().getOfferings()) {
            if (offering.getFaculty() != null) {
                String facultyName = offering.getFaculty().getPerson().getFullName().toLowerCase();
                if (facultyName.contains(searchLower)) {
                    results.add(offering);
                }
            }
        }

        return results;
    }

    private ArrayList<CourseOffering> searchCourses(String query, String filterType) {
        ArrayList<CourseOffering> results = new ArrayList<>();
        for (CourseOffering co : business.getCourseDirectory().getOfferings()) {
            switch (filterType) {
                case "Course ID":
                    if (co.getCourse().getCourseId().equalsIgnoreCase(query)) {
                        results.add(co);
                    }
                    break;
                case "Course Name":
                    if (co.getCourse().getCourseName().toLowerCase().contains(query.toLowerCase())) {
                        results.add(co);
                    }
                    break;
                case "Faculty":
                    if (co.getFaculty().getPerson().toString().toLowerCase().contains(query.toLowerCase())) {
                        results.add(co);
                    }
                    break;
            }
        }
        return results;
    }

    private void initializeSearchFilter() {
        cmbFilter.removeAllItems();
        cmbFilter.addItem("Course ID");
        cmbFilter.addItem("Faculty");
        cmbFilter.addItem("Semester");
    }

    private int getCurrentSemesterCourseCount(String semester) {
        int count = 0;
        for (Enrollment e : studentProfile.getEnrollments()) {
            if (e.getOffering().getSemester().equalsIgnoreCase(semester)
                    && !e.getStatus().equalsIgnoreCase("Dropped")) {
                count++;
            }
        }
        return count;
    }

    private boolean hasAlreadyTakenCourse(String courseId) {
        return studentProfile.getTranscript().hasCompletedCourse(courseId);
    }

    private boolean isAlreadyEnrolled(CourseOffering offering) {
        for (Enrollment e : studentProfile.getEnrollments()) {
            if (e.getOffering() == offering
                    && !e.getStatus().equalsIgnoreCase("Dropped")) {
                return true;
            }
        }
        return false;
    }

    private void loadAllCourses() {
        displayedCourses = business.getCourseDirectory().getOfferings();
        populateCoursesTable(displayedCourses);
    }

    private void populateCoursesTable(ArrayList<CourseOffering> offerings) {
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();

        model.setRowCount(0);

        for (CourseOffering offering : offerings) {
            Course course = offering.getCourse();

            int enrolled = offering.getActiveEnrollmentCount();
            int capacity = offering.getCapacity();
            String capacityInfo = enrolled + "/" + capacity;

            String facultyName = offering.getFaculty() != null
                    ? offering.getFaculty().getPerson().getFullName() : "TBA";

            String enrollmentStatus = offering.isEnrollmentOpen() ? "Open" : "Closed";

            Object[] row = new Object[7];
            row[0] = course.getCourseId();
            row[1] = course.getCourseName();
            row[2] = course.getDescription();
            row[3] = offering.getSemester();
            row[4] = capacityInfo;
            row[5] = facultyName;
            row[6] = enrollmentStatus;

            model.addRow(row);
        }
        tblCourses.setDefaultEditor(Object.class, null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourses;
    // End of variables declaration//GEN-END:variables
}
