/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Course.CourseOffering;
import Business.Course.Enrollment;
import Business.Profiles.CourseDirectory;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chinm
 */
public class CourseRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseRegistrationJPanel
     */
    private ArrayList<CourseOffering> allOfferings;
    private StudentProfile student;
    private JPanel cardSequencePanel;
    private Business business;

    public CourseRegistrationJPanel(JPanel cardSequencePanel, StudentProfile student, Business business) {
        initComponents();
        this.student = student;
        this.cardSequencePanel = cardSequencePanel;
        this.allOfferings = new ArrayList<>();
        this.business = business;
        populateTable(allOfferings, business);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEnroll = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        cmbFilter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        fieldSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(215, 204, 200));

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CourseID", "Title", "Description", "Schedule", "Capacity", "Faculty", "EnrollmentOpen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourses);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Register for Courses");

        btnEnroll.setText("Enroll ");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course ID", "Course Name", "Faculty Name" }));

        jLabel2.setText("Search By");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(402, 402, 402)
                                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(212, 212, 212)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnback))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        CardLayout layout = (CardLayout) cardSequencePanel.getLayout();
        layout.show(cardSequencePanel, "StudentWorkAreaJPanel");
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        int selectedRow = tblCourses.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a course.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
        CourseOffering co = (CourseOffering) model.getValueAt(selectedRow, 0);

        if (co == null) {
            JOptionPane.showMessageDialog(this, "No course found for the selected row.");
            return;
        }

        if (!co.isEnrollmentOpen()) {
            JOptionPane.showMessageDialog(this, "Enrollment not activated by faculty.");
            return;
        }

        int currentCredits = student.getCurrentTermCredits(co.getSemester());
        if (currentCredits + co.getCourse().getCreditHours() > 8) {
            JOptionPane.showMessageDialog(this, "You cannot take more than 8 credits this semester.");
            return;
        }

        Enrollment e = new Enrollment(student, co);
        boolean success = co.enrollStudent(e);

        if (success) {
            student.addEnrollment(e);
            JOptionPane.showMessageDialog(this, "Enrolled successfully in " + co.getCourse().getCourseName());
        } else {
            JOptionPane.showMessageDialog(this, "Enrollment failed (capacity full).");
        }
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String query = fieldSearch.getText().trim();
        if (query.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter a search term.");
            return;
        }
        String filter = (String) cmbFilter.getSelectedItem();
        ArrayList<CourseOffering> results = searchCourses(query, filter);
        populateCoursesTable(results);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void populateTable(ArrayList<CourseOffering> offerings, Business b) {
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
        model.setRowCount(0);

        CourseDirectory cd = b.getCourseDirectory();

        for (CourseOffering co : cd.getOfferings()) {
            model.addRow(new Object[]{
                co.getCourse().getCourseId(),
                co.getCourse().getCourseName(),
                co.getFaculty().getPerson().getPersonId(),
                co.getCourse().getCreditHours(),
                co.getCapacity(),
                co.getFaculty(),
                co.isEnrollmentOpen() ? "Open" : "Closed"
            });
        }
    }

    private void populateCoursesTable(ArrayList<CourseOffering> offerings) {
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
        model.setRowCount(0);
        for (CourseOffering co : offerings) {
            Object[] row = new Object[7];
            row[0] = co;
            row[1] = co.getCourse().getCourseName();
            row[2] = co.getCourse().getDescription();
            row[3] = co.getSemester();
            row[4] = co.getCapacity();
            //x`row[5] = co.getFaculty().getPerson().getName();
            row[6] = co.isEnrollmentOpen() ? "Open" : "Closed";
            model.addRow(row);
        }
    }

    private ArrayList<CourseOffering> searchCourses(String query, String filterType) {
        ArrayList<CourseOffering> results = new ArrayList<>();
        for (CourseOffering co : business.getCourseDirectory().getOfferings()) {
            switch (filterType) {
                case "Course ID":
                    if (co.getCourse().getCourseId().equalsIgnoreCase(query)) {
                        results.add(co);
                    }
                    break;
                case "Course Name":
                    if (co.getCourse().getCourseName().toLowerCase().contains(query.toLowerCase())) {
                        results.add(co);
                    }
                    break;
                case "Faculty":
                    if (co.getFaculty().getPerson().toString().toLowerCase().contains(query.toLowerCase())) {
                        results.add(co);
                    }
                    break;
            }
        }
        return results;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourses;
    // End of variables declaration//GEN-END:variables
}
