/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {

    private Business business;
    private StudentProfile studentProfile;
    private JPanel cardSequencePanel;
    private JPanel currentPanel;

    /**
     * Creates new form UnitRiskWorkArea
     *
     * @param b
     * @param spp
     * @param clp
     */
    public StudentWorkAreaJPanel(Business business, StudentProfile studentProfile, JPanel cardSequencePanel) {
        this.business = business;
        this.studentProfile = studentProfile;
        this.cardSequencePanel = cardSequencePanel;
        initComponents();
        lblTitle.setText("Welcome, " + studentProfile.getPerson().getFullName() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCourseManagement = new javax.swing.JButton();
        btnManageProfile = new javax.swing.JButton();
        btnGraduationAudit = new javax.swing.JButton();
        btnCourseRegistration = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnTranscriptReview = new javax.swing.JButton();
        btnFinancialManagement = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(215, 204, 200));
        setForeground(new java.awt.Color(51, 51, 51));

        btnCourseManagement.setBackground(new java.awt.Color(176, 190, 197));
        btnCourseManagement.setFont(getFont());
        btnCourseManagement.setText("Course Work Management");
        btnCourseManagement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCourseManagement.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCourseManagement.setMinimumSize(new java.awt.Dimension(20, 23));
        btnCourseManagement.setPreferredSize(new java.awt.Dimension(240, 30));
        btnCourseManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseManagementIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageProfile.setBackground(new java.awt.Color(176, 190, 197));
        btnManageProfile.setFont(getFont());
        btnManageProfile.setText("Manage Profile");
        btnManageProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageProfile.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });

        btnGraduationAudit.setBackground(new java.awt.Color(176, 190, 197));
        btnGraduationAudit.setFont(getFont());
        btnGraduationAudit.setText("Graduation Audit");
        btnGraduationAudit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGraduationAudit.setMaximumSize(new java.awt.Dimension(200, 40));
        btnGraduationAudit.setMinimumSize(new java.awt.Dimension(20, 20));
        btnGraduationAudit.setPreferredSize(new java.awt.Dimension(240, 25));
        btnGraduationAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduationAuditActionPerformed(evt);
            }
        });

        btnCourseRegistration.setBackground(new java.awt.Color(176, 190, 197));
        btnCourseRegistration.setFont(getFont());
        btnCourseRegistration.setText("Course Registration");
        btnCourseRegistration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCourseRegistration.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCourseRegistration.setMinimumSize(new java.awt.Dimension(20, 20));
        btnCourseRegistration.setPreferredSize(new java.awt.Dimension(240, 25));
        btnCourseRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseRegistrationActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setText("My Student Portal");

        btnTranscriptReview.setBackground(new java.awt.Color(176, 190, 197));
        btnTranscriptReview.setFont(getFont());
        btnTranscriptReview.setText("Transcript Review");
        btnTranscriptReview.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTranscriptReview.setMaximumSize(new java.awt.Dimension(200, 40));
        btnTranscriptReview.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTranscriptReview.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTranscriptReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptReviewActionPerformed(evt);
            }
        });

        btnFinancialManagement.setBackground(new java.awt.Color(176, 190, 197));
        btnFinancialManagement.setFont(getFont());
        btnFinancialManagement.setText("Pay Tution");
        btnFinancialManagement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFinancialManagement.setMaximumSize(new java.awt.Dimension(200, 40));
        btnFinancialManagement.setMinimumSize(new java.awt.Dimension(20, 20));
        btnFinancialManagement.setPreferredSize(new java.awt.Dimension(240, 25));
        btnFinancialManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinancialManagementActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(176, 190, 197));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCourseManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btnManageProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btnTranscriptReview, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFinancialManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btnGraduationAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btnCourseRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraduationAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTranscriptReview, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinancialManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseManagementIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseManagementIdentifyResourceAssetsActionPerformed

        System.out.println("Navigating to Course Work Management");
        System.out.println("Student Profile: " + studentProfile.getPerson().getFullName());
        System.out.println("Total Enrollments: " + studentProfile.getEnrollments().size());

        CourseWorkManagementJPanel panel = new CourseWorkManagementJPanel(business, studentProfile, cardSequencePanel);
        navigateToPanel(panel, "CourseWorkManagement");

    }//GEN-LAST:event_btnCourseManagementIdentifyResourceAssetsActionPerformed

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        ManageProfileJPanel panel = new ManageProfileJPanel(business, studentProfile, cardSequencePanel);
        navigateToPanel(panel, "ManageProfile");
}//GEN-LAST:event_btnManageProfileActionPerformed

    private void btnGraduationAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduationAuditActionPerformed
        GraduationAuditJPanel panel = new GraduationAuditJPanel(business, studentProfile, cardSequencePanel);
        navigateToPanel(panel, "GraduationAudit");
    }//GEN-LAST:event_btnGraduationAuditActionPerformed

    private void btnCourseRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseRegistrationActionPerformed
        System.out.println("Navigating to Course Registration");
        System.out.println("Student Profile: " + studentProfile.getPerson().getFullName());
        System.out.println("Total Enrollments: " + studentProfile.getEnrollments().size());

        CourseRegistrationJPanel panel = new CourseRegistrationJPanel(business, studentProfile, cardSequencePanel);
        navigateToPanel(panel, "CourseRegistration");
}//GEN-LAST:event_btnCourseRegistrationActionPerformed

    private void btnTranscriptReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptReviewActionPerformed
        double balance = studentProfile.getAccount().getOutstandingBalance();

        if (balance > 0) {
            JOptionPane.showMessageDialog(this,
                    "You cannot view your transcript until all tuition is paid.\n"
                    + "Outstanding Balance: $" + String.format("%.2f", balance),
                    "Transcript Access Denied",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        TranscriptReviewJPanel panel = new TranscriptReviewJPanel(business, studentProfile, cardSequencePanel);
        navigateToPanel(panel, "TranscriptReview");
    }//GEN-LAST:event_btnTranscriptReviewActionPerformed

    private void btnFinancialManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinancialManagementActionPerformed
        PayTuitionJPanel panel = new PayTuitionJPanel(business, studentProfile, cardSequencePanel);
        navigateToPanel(panel, "PayTuition");
    }//GEN-LAST:event_btnFinancialManagementActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int response = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to logout?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            cardSequencePanel.removeAll();

            javax.swing.JLabel welcomeLabel = new javax.swing.JLabel();
            welcomeLabel.setFont(new java.awt.Font("Dialog", 0, 24));
            welcomeLabel.setForeground(new java.awt.Color(102, 153, 255));
            welcomeLabel.setText("Education Going Digital .... Info 5100");
            welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

            cardSequencePanel.add(welcomeLabel, "welcome");
            ((java.awt.CardLayout) cardSequencePanel.getLayout()).show(cardSequencePanel, "welcome");

            cardSequencePanel.revalidate();
            cardSequencePanel.repaint();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void navigateToPanel(JPanel panel, String panelName) {
        cardSequencePanel.add(panel, panelName);
        ((java.awt.CardLayout) cardSequencePanel.getLayout()).show(cardSequencePanel, panelName);
        cardSequencePanel.revalidate();
        cardSequencePanel.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseManagement;
    private javax.swing.JButton btnCourseRegistration;
    private javax.swing.JButton btnFinancialManagement;
    private javax.swing.JButton btnGraduationAudit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnTranscriptReview;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
