/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.AdminRole;

import Business.Business;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.ManagePersonsJPanel;
import javax.swing.JPanel;

/**
 *
 * @author pranjalpatil
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {

    private JPanel CardSequencePanel;
    private Business business;

    /**
     * Creates new form AdminWorkAreaPanel
     */
    public AdminWorkAreaPanel(Business business, JPanel CardSequencePanel) {
        initComponents();
        this.business = business;
        this.CardSequencePanel = CardSequencePanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMngPersons = new javax.swing.JButton();
        btnMngCourses = new javax.swing.JButton();
        btnMngAcc = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblWelcomeAdmin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        btnMngPersons.setBackground(new java.awt.Color(0, 255, 255));
        btnMngPersons.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnMngPersons.setForeground(new java.awt.Color(0, 102, 102));
        btnMngPersons.setText("Manage Persons");
        btnMngPersons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMngPersons.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMngPersons.setMinimumSize(new java.awt.Dimension(20, 23));
        btnMngPersons.setPreferredSize(new java.awt.Dimension(240, 30));
        btnMngPersons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngPersonsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnMngCourses.setBackground(new java.awt.Color(0, 255, 255));
        btnMngCourses.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnMngCourses.setForeground(new java.awt.Color(0, 102, 102));
        btnMngCourses.setText("Manage Courses");
        btnMngCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMngCourses.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMngCourses.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMngCourses.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMngCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngCoursesActionPerformed(evt);
            }
        });

        btnMngAcc.setBackground(new java.awt.Color(0, 255, 255));
        btnMngAcc.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnMngAcc.setForeground(new java.awt.Color(0, 102, 102));
        btnMngAcc.setText("Manage Accounts");
        btnMngAcc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMngAcc.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMngAcc.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMngAcc.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMngAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngAccActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 255, 255));
        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 102, 102));
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setMaximumSize(new java.awt.Dimension(145, 40));
        btnLogout.setMinimumSize(new java.awt.Dimension(20, 20));
        btnLogout.setPreferredSize(new java.awt.Dimension(240, 25));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutIdentifyEventsActionPerformed(evt);
            }
        });

        lblWelcomeAdmin.setBackground(new java.awt.Color(0, 255, 255));
        lblWelcomeAdmin.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        lblWelcomeAdmin.setForeground(new java.awt.Color(0, 255, 255));
        lblWelcomeAdmin.setText("Welcome Admin!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblWelcomeAdmin)
                        .addGap(279, 279, 279))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMngPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(btnMngAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(btnMngCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblWelcomeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMngAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMngPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(btnMngCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngPersonsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngPersonsIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:

        //ManageUserAccountsJPanel aos = new ManageUserAccountsJPanel(business, CardSequencePanel);

//        CardSequencePanel.add("ManageVulns", aos);
//        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnMngPersonsIdentifyResourceAssetsActionPerformed

    private void btnMngCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngCoursesActionPerformed

    }//GEN-LAST:event_btnMngCoursesActionPerformed

    private void btnMngAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngAccActionPerformed
        // TODO add your handling code here:

        ManagePersonsJPanel aos = new ManagePersonsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("Manage Persons", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnMngAccActionPerformed

    private void btnLogoutIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutIdentifyEventsActionPerformed

    }//GEN-LAST:event_btnLogoutIdentifyEventsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMngAcc;
    private javax.swing.JButton btnMngCourses;
    private javax.swing.JButton btnMngPersons;
    private javax.swing.JLabel lblWelcomeAdmin;
    // End of variables declaration//GEN-END:variables
}
