/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Business;
import Business.Course.CourseOffering;
import Business.Course.Enrollment;
import Business.CourseWork.Assignment;
import Business.CourseWork.Submission;
import Business.Person.Person;
import Business.Profiles.FacultyProfile;
import Business.Profiles.StudentProfile;
import java.awt.Color;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Locale;
import java.util.Map;

/**
 *
 * @author anishagaikar
 */
public class FacultyConsole extends javax.swing.JPanel {

    private final Business business;
    private final JPanel cardPanel;
    private final FacultyProfile facultyProfile;
    private DefaultTableModel courseModel;
    private DefaultTableModel studentModel;
    private DefaultTableModel reportModel;
    private DefaultTableModel tuitionModel;
    private NumberFormat currencyFormat;
    private SimpleDateFormat dateFormat;
    private CourseOffering selectedCourse;

    public FacultyConsole(Business business, FacultyProfile facultyProfile, JPanel cardSequencePanel) {
        this.business = business;
        this.facultyProfile = facultyProfile;
        this.cardPanel = cardSequencePanel;
        this.currencyFormat = NumberFormat.getCurrencyInstance(Locale.US);
        this.dateFormat = new SimpleDateFormat("MM/dd/yyyy");

        initComponents();
        initAfterGui();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCourses = new javax.swing.JPanel();
        btnOpenEnrollment = new javax.swing.JButton();
        btnCloseEnrollment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnCourseSaveSyllabus = new javax.swing.JButton();
        btnCourseBack = new javax.swing.JButton();
        jPanelStudents = new javax.swing.JPanel();
        cboCourses = new javax.swing.JComboBox<>();
        lblStudentCourse = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnStudentTranscript = new javax.swing.JButton();
        btnStudentGrade = new javax.swing.JButton();
        btnStudentViewRanking = new javax.swing.JButton();
        btnStudentBack = new javax.swing.JButton();
        jPanelProfiles = new javax.swing.JPanel();
        lblProfileFacultyID = new javax.swing.JLabel();
        lblProfilesName = new javax.swing.JLabel();
        lblProfilesEmail = new javax.swing.JLabel();
        lblProfilesPhone = new javax.swing.JLabel();
        lblProfilesDepartment = new javax.swing.JLabel();
        lblProfilesOfficehrs = new javax.swing.JLabel();
        txtProfilesFacultyID = new javax.swing.JTextField();
        txtProfileName = new javax.swing.JTextField();
        txtProfilesEmail = new javax.swing.JTextField();
        txtProfilesPhone = new javax.swing.JTextField();
        txtProfilesDepatment = new javax.swing.JTextField();
        txtProfileOfficeHrs = new javax.swing.JTextField();
        btnProfilesEdit = new javax.swing.JButton();
        btnProfilesSave = new javax.swing.JButton();
        btnProfilesBack = new javax.swing.JButton();
        lblReportsSemester = new javax.swing.JPanel();
        lblReportSemester = new javax.swing.JLabel();
        lblReportsCourse = new javax.swing.JLabel();
        cboReportSemester = new javax.swing.JComboBox<>();
        cboReportsCourse = new javax.swing.JComboBox<>();
        btnReportsLoad = new javax.swing.JButton();
        btnReportsExport = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();
        btnReportsBack = new javax.swing.JButton();
        jPanelTuition = new javax.swing.JPanel();
        tblTuition = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnTuitionBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jTabbedPane1.setBackground(new java.awt.Color(0, 204, 204));

        jPanelCourses.setBackground(new java.awt.Color(0, 153, 153));

        btnOpenEnrollment.setText("Open Enrolment");
        btnOpenEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenEnrollmentActionPerformed(evt);
            }
        });

        btnCloseEnrollment.setText("close Enrollment");
        btnCloseEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseEnrollmentActionPerformed(evt);
            }
        });

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Title", "Description", "Capacity", "Room", "time"
            }
        ));
        jScrollPane1.setViewportView(tblCourses);

        btnUpdate.setText("Update ");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCourseSaveSyllabus.setText("Save Syllabus");
        btnCourseSaveSyllabus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseSaveSyllabusActionPerformed(evt);
            }
        });

        btnCourseBack.setText("Back");
        btnCourseBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCoursesLayout = new javax.swing.GroupLayout(jPanelCourses);
        jPanelCourses.setLayout(jPanelCoursesLayout);
        jPanelCoursesLayout.setHorizontalGroup(
            jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCoursesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCourseBack)
                .addGap(184, 184, 184))
            .addGroup(jPanelCoursesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelCoursesLayout.createSequentialGroup()
                        .addComponent(btnOpenEnrollment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCloseEnrollment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCourseSaveSyllabus)
                        .addGap(0, 247, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCoursesLayout.setVerticalGroup(
            jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCoursesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCourseBack)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenEnrollment)
                    .addComponent(btnCloseEnrollment)
                    .addComponent(btnUpdate)
                    .addComponent(btnCourseSaveSyllabus))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Courses Management", jPanelCourses);

        jPanelStudents.setBackground(new java.awt.Color(0, 153, 153));

        cboCourses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cboCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCoursesActionPerformed(evt);
            }
        });

        lblStudentCourse.setText("Courses");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Email", "Total%", "Letter", "GPA"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnStudentTranscript.setText("Access Transcript");
        btnStudentTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentTranscriptActionPerformed(evt);
            }
        });

        btnStudentGrade.setText("Grade Assigning");
        btnStudentGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentGradeActionPerformed(evt);
            }
        });

        btnStudentViewRanking.setText("view Ranking");
        btnStudentViewRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentViewRankingActionPerformed(evt);
            }
        });

        btnStudentBack.setText("Back");
        btnStudentBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStudentsLayout = new javax.swing.GroupLayout(jPanelStudents);
        jPanelStudents.setLayout(jPanelStudentsLayout);
        jPanelStudentsLayout.setHorizontalGroup(
            jPanelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentsLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnStudentTranscript)
                .addGap(18, 18, 18)
                .addComponent(btnStudentGrade)
                .addGap(30, 30, 30)
                .addComponent(btnStudentViewRanking)
                .addContainerGap(243, Short.MAX_VALUE))
            .addGroup(jPanelStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStudentCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStudentBack)
                .addGap(71, 71, 71))
            .addGroup(jPanelStudentsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanelStudentsLayout.setVerticalGroup(
            jPanelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentCourse)
                    .addComponent(btnStudentBack))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentTranscript)
                    .addComponent(btnStudentGrade)
                    .addComponent(btnStudentViewRanking))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Students Management", jPanelStudents);

        jPanelProfiles.setBackground(new java.awt.Color(0, 153, 153));

        lblProfileFacultyID.setText("Faculty ID");

        lblProfilesName.setText("Name");

        lblProfilesEmail.setText("Email ID");

        lblProfilesPhone.setText("Phone");

        lblProfilesDepartment.setText("Department");

        lblProfilesOfficehrs.setText("Office Hrs");

        txtProfilesDepatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfilesDepatmentActionPerformed(evt);
            }
        });

        btnProfilesEdit.setText("Edit");
        btnProfilesEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilesEditActionPerformed(evt);
            }
        });

        btnProfilesSave.setText("Save");
        btnProfilesSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilesSaveActionPerformed(evt);
            }
        });

        btnProfilesBack.setText("Back");
        btnProfilesBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilesBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProfilesLayout = new javax.swing.GroupLayout(jPanelProfiles);
        jPanelProfiles.setLayout(jPanelProfilesLayout);
        jPanelProfilesLayout.setHorizontalGroup(
            jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfilesLayout.createSequentialGroup()
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProfilesLayout.createSequentialGroup()
                        .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProfilesLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblProfilesEmail))
                            .addGroup(jPanelProfilesLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblProfileFacultyID)
                                    .addComponent(lblProfilesPhone)
                                    .addComponent(lblProfilesDepartment)
                                    .addComponent(lblProfilesOfficehrs)
                                    .addComponent(lblProfilesName))))
                        .addGap(68, 68, 68)
                        .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtProfileOfficeHrs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(txtProfilesPhone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProfilesEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProfileName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProfilesFacultyID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProfilesDepatment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                        .addComponent(btnProfilesBack))
                    .addGroup(jPanelProfilesLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnProfilesEdit)
                        .addGap(79, 79, 79)
                        .addComponent(btnProfilesSave)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(56, 56, 56))
        );
        jPanelProfilesLayout.setVerticalGroup(
            jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfilesLayout.createSequentialGroup()
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProfilesLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProfileFacultyID)
                            .addComponent(txtProfilesFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelProfilesLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnProfilesBack)))
                .addGap(18, 18, 18)
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfilesName)
                    .addComponent(txtProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfilesEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfilesEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfilesPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfilesPhone))
                .addGap(16, 16, 16)
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfilesDepatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfilesDepartment))
                .addGap(18, 18, 18)
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfileOfficeHrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfilesOfficehrs))
                .addGap(85, 85, 85)
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfilesEdit)
                    .addComponent(btnProfilesSave))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Profiles Management", jPanelProfiles);

        lblReportsSemester.setBackground(new java.awt.Color(0, 153, 153));

        lblReportSemester.setText("Semester");

        lblReportsCourse.setText("Course");

        btnReportsLoad.setText("Load");
        btnReportsLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsLoadActionPerformed(evt);
            }
        });

        btnReportsExport.setText("Export");
        btnReportsExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsExportActionPerformed(evt);
            }
        });

        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Letter Grade", "Count", "Percentage%"
            }
        ));
        jScrollPane4.setViewportView(tblReports);
        if (tblReports.getColumnModel().getColumnCount() > 0) {
            tblReports.getColumnModel().getColumn(2).setResizable(false);
        }

        btnReportsBack.setText("Back");
        btnReportsBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblReportsSemesterLayout = new javax.swing.GroupLayout(lblReportsSemester);
        lblReportsSemester.setLayout(lblReportsSemesterLayout);
        lblReportsSemesterLayout.setHorizontalGroup(
            lblReportsSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblReportsSemesterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReportsBack)
                .addGap(71, 71, 71))
            .addGroup(lblReportsSemesterLayout.createSequentialGroup()
                .addGroup(lblReportsSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblReportsSemesterLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lblReportsSemesterLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(lblReportsSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReportsExport)
                            .addGroup(lblReportsSemesterLayout.createSequentialGroup()
                                .addComponent(lblReportSemester)
                                .addGap(18, 18, 18)
                                .addComponent(cboReportSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(lblReportsCourse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboReportsCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReportsLoad)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        lblReportsSemesterLayout.setVerticalGroup(
            lblReportsSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblReportsSemesterLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(lblReportsSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReportSemester)
                    .addComponent(lblReportsCourse)
                    .addComponent(cboReportSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboReportsCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportsLoad))
                .addGap(18, 18, 18)
                .addComponent(btnReportsExport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportsBack)
                .addGap(98, 98, 98))
        );

        jTabbedPane1.addTab("Performance Reports", lblReportsSemester);

        jPanelTuition.setBackground(new java.awt.Color(0, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Billed", "Paid", "Remaining Due"
            }
        ));
        tblTuition.setViewportView(jTable1);

        btnTuitionBack.setText("Back");
        btnTuitionBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuitionBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTuitionLayout = new javax.swing.GroupLayout(jPanelTuition);
        jPanelTuition.setLayout(jPanelTuitionLayout);
        jPanelTuitionLayout.setHorizontalGroup(
            jPanelTuitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTuitionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTuitionBack)
                .addGap(42, 42, 42))
            .addGroup(jPanelTuitionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tblTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelTuitionLayout.setVerticalGroup(
            jPanelTuitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTuitionLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(tblTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnTuitionBack)
                .addGap(65, 65, 65))
        );

        jTabbedPane1.addTab("Enrollment Insighnt", jPanelTuition);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentGradeActionPerformed
        if (selectedCourse == null) {
            JOptionPane.showMessageDialog(this, "Select a course first.");
            return;
        }

        int row = jTable2.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Select a student to grade.");
            return;
        }

        int modelRow = jTable2.convertRowIndexToModel(row);
        String studentId = String.valueOf(studentModel.getValueAt(modelRow, 0));

        ArrayList<Assignment> assignments = selectedCourse.getAssignments();

        if (assignments.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No assignments exist for this course yet.",
                    "No Assignments",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String[] assignmentNames = new String[assignments.size()];
        for (int i = 0; i < assignments.size(); i++) {
            assignmentNames[i] = assignments.get(i).getTitle();
        }

        String selectedAssignment = (String) JOptionPane.showInputDialog(this,
                "Select assignment to grade:",
                "Grade Assignment",
                JOptionPane.QUESTION_MESSAGE,
                null,
                assignmentNames,
                assignmentNames[0]);

        if (selectedAssignment == null) {
            return;
        }

        Assignment assignment = null;
        for (Assignment a : assignments) {
            if (a.getTitle().equals(selectedAssignment)) {
                assignment = a;
                break;
            }
        }

        if (assignment == null) {
            return;
        }

        Submission submission = assignment.findSubmissionByStudent(studentId);

        if (submission == null) {
            JOptionPane.showMessageDialog(this,
                    "Student has not submitted this assignment yet.",
                    "No Submission",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (submission.getStatus().equals("Graded")) {
            int response = JOptionPane.showConfirmDialog(this,
                    "This assignment is already graded (" + submission.getPointsEarned() + "/"
                    + assignment.getMaxPoints() + ").\n"
                    + "Do you want to re-grade it?",
                    "Already Graded",
                    JOptionPane.YES_NO_OPTION);

            if (response != JOptionPane.YES_OPTION) {
                return;
            }
        }

        String earnedStr = JOptionPane.showInputDialog(this,
                "Points Earned (Max: " + assignment.getMaxPoints() + "):",
                "Grade Assignment",
                JOptionPane.QUESTION_MESSAGE);

        if (earnedStr == null || earnedStr.trim().isEmpty()) {
            return;
        }

        try {
            int pointsEarned = Integer.parseInt(earnedStr);

            if (pointsEarned < 0 || pointsEarned > assignment.getMaxPoints()) {
                JOptionPane.showMessageDialog(this,
                        "Points must be between 0 and " + assignment.getMaxPoints(),
                        "Invalid Points",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            String feedback = JOptionPane.showInputDialog(this,
                    "Feedback (optional):",
                    "Grade Assignment",
                    JOptionPane.QUESTION_MESSAGE);

            submission.setPointsEarned(pointsEarned);
            submission.setFeedback(feedback != null ? feedback : "");
            submission.setStatus("Graded");

            JOptionPane.showMessageDialog(this,
                    "Grade saved successfully!\n\n"
                    + "Points: " + pointsEarned + "/" + assignment.getMaxPoints() + "\n"
                    + "Percentage: " + String.format("%.2f%%", (pointsEarned * 100.0 / assignment.getMaxPoints())),
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            selectCourseFromCombo();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a valid number",
                    "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnStudentGradeActionPerformed

    private void btnOpenEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenEnrollmentActionPerformed
        int row = tblCourses.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Select a course row first.");
            return;
        }

        int modelRow = tblCourses.convertRowIndexToModel(row);
        String courseId = String.valueOf(courseModel.getValueAt(modelRow, 0));

        for (CourseOffering offering : facultyProfile.getOfferings()) {
            if (offering.getCourse().getCourseId().equals(courseId)) {
                offering.setEnrollmentOpen(true);
                JOptionPane.showMessageDialog(this, "Enrollment opened for " + courseId);
                refreshCoursesTable();
                return;
            }
        }

    }//GEN-LAST:event_btnOpenEnrollmentActionPerformed

    private void txtProfilesDepatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfilesDepatmentActionPerformed

    }//GEN-LAST:event_txtProfilesDepatmentActionPerformed

    private void btnProfilesSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilesSaveActionPerformed
        Person person = facultyProfile.getPerson();

        person.setEmail(txtProfilesEmail.getText().trim());
        person.setPhone(txtProfilesPhone.getText().trim());
        person.setDepartment(txtProfilesDepatment.getText().trim());
        facultyProfile.setDepartment(txtProfilesDepatment.getText().trim());

        txtProfilesEmail.setEditable(false);
        txtProfilesPhone.setEditable(false);
        txtProfilesDepatment.setEditable(false);
        txtProfileOfficeHrs.setEditable(false);

        Color gray = new Color(220, 220, 220);
        txtProfilesEmail.setBackground(gray);
        txtProfilesPhone.setBackground(gray);
        txtProfilesDepatment.setBackground(gray);
        txtProfileOfficeHrs.setBackground(gray);

        JOptionPane.showMessageDialog(this, "Profile saved.");
    }//GEN-LAST:event_btnProfilesSaveActionPerformed

    private void btnReportsLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsLoadActionPerformed
        String sem = (String) cboReportSemester.getSelectedItem();
        String courseSel = (String) cboReportsCourse.getSelectedItem();

        if (sem == null || courseSel == null) {
            JOptionPane.showMessageDialog(this, "Select semester & course.");
            return;
        }

        String courseId = courseSel.substring(0, courseSel.indexOf(" - "));

        CourseOffering reportCourse = null;
        for (CourseOffering offering : facultyProfile.getOfferings()) {
            if (offering.getCourse().getCourseId().equals(courseId)
                    && offering.getSemester().equals(sem)) {
                reportCourse = offering;
                break;
            }
        }

        if (reportCourse == null) {
            return;
        }

        Map<String, Integer> distribution = new HashMap<>();
        String[] grades = {"A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "F"};
        for (String g : grades) {
            distribution.put(g, 0);
        }

        int totalStudents = 0;
        double totalPercent = 0;

        for (Enrollment enrollment : reportCourse.getEnrollments()) {
            if (enrollment.getStatus().equalsIgnoreCase("Dropped")) {
                continue;
            }

            double percent = calculateStudentPercentage(reportCourse, enrollment.getStudent());
            String letter = toLetter(percent);

            distribution.put(letter, distribution.get(letter) + 1);
            totalPercent += percent;
            totalStudents++;
        }

        reportModel.setRowCount(0);

        int total = Math.max(1, totalStudents);
        for (String grade : grades) {
            int count = distribution.get(grade);
            double percentage = (count * 100.0) / total;
            reportModel.addRow(new Object[]{
                grade,
                count,
                String.format(Locale.US, "%.2f", percentage)
            });
        }

        double avgPercent = totalStudents == 0 ? 0 : totalPercent / totalStudents;
        double avgGpa = toGpa(toLetter(avgPercent));

        reportModel.addRow(new Object[]{"Average %", String.format(Locale.US, "%.2f", avgPercent), ""});
        reportModel.addRow(new Object[]{"Class GPA", String.format(Locale.US, "%.2f", avgGpa), ""});
    }//GEN-LAST:event_btnReportsLoadActionPerformed

    private void btnReportsExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsExportActionPerformed
        if (reportModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No report loaded.");
            return;
        }

        JOptionPane.showMessageDialog(this,
                "Export functionality would save this report as CSV.",
                "Export Report",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnReportsExportActionPerformed


    private void cboCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCoursesActionPerformed
        selectCourseFromCombo();
    }//GEN-LAST:event_cboCoursesActionPerformed

    private void btnCourseBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseBackActionPerformed
        navigateToFacultyDashboard();
    }//GEN-LAST:event_btnCourseBackActionPerformed

    private void btnCloseEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseEnrollmentActionPerformed
        int row = tblCourses.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Select a course row first.");
            return;
        }

        int modelRow = tblCourses.convertRowIndexToModel(row);
        String courseId = String.valueOf(courseModel.getValueAt(modelRow, 0));

        for (CourseOffering offering : facultyProfile.getOfferings()) {
            if (offering.getCourse().getCourseId().equals(courseId)) {
                offering.setEnrollmentOpen(false);
                JOptionPane.showMessageDialog(this, "Enrollment closed for " + courseId);
                refreshCoursesTable();
                return;
            }
        }

    }//GEN-LAST:event_btnCloseEnrollmentActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        JOptionPane.showMessageDialog(this,
                "Course update functionality.\n"
                + "In a full implementation, this would allow editing\n"
                + "course title, description, capacity, etc.",
                "Update Course",
                JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCourseSaveSyllabusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseSaveSyllabusActionPerformed
        JOptionPane.showMessageDialog(this,
                "Syllabus upload functionality.\n"
                + "In a full implementation, this would allow\n"
                + "selecting and uploading a syllabus file.",
                "Save Syllabus",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCourseSaveSyllabusActionPerformed

    private void btnStudentTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentTranscriptActionPerformed
        if (selectedCourse == null) {
            JOptionPane.showMessageDialog(this, "Select a course first.");
            return;
        }

        int row = jTable2.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Select a student.");
            return;
        }

        int modelRow = jTable2.convertRowIndexToModel(row);
        String studentId = String.valueOf(studentModel.getValueAt(modelRow, 0));

        showTranscriptDialog(studentId);
    }//GEN-LAST:event_btnStudentTranscriptActionPerformed

    private void btnStudentViewRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentViewRankingActionPerformed
        if (selectedCourse == null) {
            JOptionPane.showMessageDialog(this, "Select a course first.");
            return;
        }

        showRankingDialog();
    }//GEN-LAST:event_btnStudentViewRankingActionPerformed

    private void btnProfilesEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilesEditActionPerformed
        txtProfilesEmail.setEditable(true);
        txtProfilesPhone.setEditable(true);
        txtProfilesDepatment.setEditable(true);
        txtProfileOfficeHrs.setEditable(true);

        txtProfilesEmail.setBackground(Color.WHITE);
        txtProfilesPhone.setBackground(Color.WHITE);
        txtProfilesDepatment.setBackground(Color.WHITE);
        txtProfileOfficeHrs.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnProfilesEditActionPerformed

    private void btnStudentBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentBackActionPerformed
        navigateToFacultyDashboard();
    }//GEN-LAST:event_btnStudentBackActionPerformed

    private void btnProfilesBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilesBackActionPerformed
        navigateToFacultyDashboard();
    }//GEN-LAST:event_btnProfilesBackActionPerformed

    private void btnReportsBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsBackActionPerformed
        navigateToFacultyDashboard();
    }//GEN-LAST:event_btnReportsBackActionPerformed

    private void btnTuitionBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuitionBackActionPerformed
        navigateToFacultyDashboard();
    }//GEN-LAST:event_btnTuitionBackActionPerformed

    private void navigateToFacultyDashboard() {
        FacultyWorkAreaJPanel dashboard = new FacultyWorkAreaJPanel(business, facultyProfile, cardPanel);
        cardPanel.add(dashboard, "FacultyDashboard");
        ((java.awt.CardLayout) cardPanel.getLayout()).show(cardPanel, "FacultyDashboard");
        cardPanel.revalidate();
        cardPanel.repaint();
    }

    private void showRankingDialog() {
        class StudentRank {

            String id, name;
            double percent;
            String letter;
            double gpa;
        }

        ArrayList<StudentRank> ranks = new ArrayList<>();

        for (Enrollment enrollment : selectedCourse.getEnrollments()) {
            if (enrollment.getStatus().equalsIgnoreCase("Dropped")) {
                continue;
            }

            StudentProfile student = enrollment.getStudent();
            double percent = calculateStudentPercentage(selectedCourse, student);

            StudentRank rank = new StudentRank();
            rank.id = student.getPerson().getPersonId();
            rank.name = student.getPerson().getFullName();
            rank.percent = percent;
            rank.letter = toLetter(percent);
            rank.gpa = toGpa(rank.letter);

            ranks.add(rank);
        }

        ranks.sort((a, b) -> Double.compare(b.percent, a.percent));

        StringBuilder ranking = new StringBuilder();
        ranking.append("CLASS RANKING\n");
        ranking.append("Course: ").append(selectedCourse.getCourse().getCourseId()).append("\n\n");
        ranking.append(String.format("%-6s %-12s %-25s %10s %8s %6s\n",
                "Rank", "Student ID", "Name", "Percent", "Letter", "GPA"));
        ranking.append("═══════════════════════════════════════════════════════════════\n");

        double gpaSum = 0;
        for (int i = 0; i < ranks.size(); i++) {
            StudentRank r = ranks.get(i);
            ranking.append(String.format("%-6d %-12s %-25s %9.2f%% %8s %6.2f\n",
                    i + 1, r.id, r.name, r.percent, r.letter, r.gpa));
            gpaSum += r.gpa;
        }

        double classGpa = ranks.isEmpty() ? 0 : gpaSum / ranks.size();
        ranking.append("\n═══════════════════════════════════════════════════════════════\n");
        ranking.append(String.format("Class Average GPA: %.2f\n", classGpa));

        JOptionPane.showMessageDialog(this,
                new javax.swing.JScrollPane(new javax.swing.JTextArea(ranking.toString(), 20, 60)),
                "Class Ranking",
                JOptionPane.PLAIN_MESSAGE);
    }

    private void initAfterGui() {
        courseModel = new DefaultTableModel(
                new Object[]{"Course ID", "Title", "Description", "Capacity", "Room", "Time"}, 0) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        tblCourses.setModel(courseModel);

        studentModel = new DefaultTableModel(
                new Object[]{"Student ID", "Name", "Email", "Total%", "Letter", "GPA"}, 0) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        jTable2.setModel(studentModel);

        reportModel = new DefaultTableModel(
                new Object[]{"Letter Grade", "Count", "Percentage%"}, 0) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        tblReports.setModel(reportModel);

        tuitionModel = new DefaultTableModel(
                new Object[]{"Student ID", "Student Name", "Course ID", "Billed", "Paid", "Remaining Due"}, 0) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        jTable1.setModel(tuitionModel);

        loadFacultyProfile();
        refreshCoursesTable();
        loadCourseCombo();
        loadReportSemesterCombo();
        loadTuitionTable();
    }

    private void loadFacultyProfile() {
        Person person = facultyProfile.getPerson();
        txtProfilesFacultyID.setText(person.getPersonId());
        txtProfileName.setText(person.getFullName());
        txtProfilesEmail.setText(person.getEmail());
        txtProfilesPhone.setText(person.getPhone() != null ? person.getPhone() : "");
        txtProfilesDepatment.setText(facultyProfile.getDepartment() != null ? facultyProfile.getDepartment() : "");
        txtProfileOfficeHrs.setText("");

        txtProfilesFacultyID.setEditable(false);
        txtProfileName.setEditable(false);
        txtProfilesEmail.setEditable(false);
        txtProfilesPhone.setEditable(false);
        txtProfilesDepatment.setEditable(false);
        txtProfileOfficeHrs.setEditable(false);
    }

    private void refreshCoursesTable() {
        courseModel.setRowCount(0);

        for (CourseOffering offering : facultyProfile.getOfferings()) {
            Object[] row = new Object[6];
            row[0] = offering.getCourse().getCourseId();
            row[1] = offering.getCourse().getCourseName();
            row[2] = offering.getCourse().getDescription();
            row[3] = offering.getCapacity();
            row[4] = "";
            row[5] = offering.getSemester();

            courseModel.addRow(row);
        }
    }

    private void showTranscriptDialog(String studentId) {
        StringBuilder transcript = new StringBuilder();
        transcript.append("ASSIGNMENT TRANSCRIPT\n");
        transcript.append("Course: ").append(selectedCourse.getCourse().getCourseId())
                .append(" - ").append(selectedCourse.getCourse().getCourseName()).append("\n");
        transcript.append("Student: ").append(studentId).append("\n\n");
        transcript.append("═══════════════════════════════════════════════════\n\n");

        double earnedTotal = 0;
        double maxTotal = 0;

        transcript.append(String.format("%-25s %10s %10s %10s\n", "Assignment", "Earned", "Max", "Percent"));
        transcript.append("─────────────────────────────────────────────────\n");

        for (Assignment assignment : selectedCourse.getAssignments()) {
            Submission submission = assignment.findSubmissionByStudent(studentId);

            if (submission != null && submission.getStatus().equals("Graded")) {
                double percent = (submission.getPointsEarned() * 100.0) / assignment.getMaxPoints();
                transcript.append(String.format("%-25s %10.0f %10.0f %9.2f%%\n",
                        assignment.getTitle(),
                        (double) submission.getPointsEarned(),
                        (double) assignment.getMaxPoints(),
                        percent));

                earnedTotal += submission.getPointsEarned();
                maxTotal += assignment.getMaxPoints();
            } else {
                transcript.append(String.format("%-25s %10s %10.0f %10s\n",
                        assignment.getTitle(),
                        "N/A",
                        (double) assignment.getMaxPoints(),
                        "N/A"));
            }
        }

        transcript.append("\n═══════════════════════════════════════════════════\n");
        double totalPercent = maxTotal == 0 ? 0 : (earnedTotal / maxTotal) * 100.0;
        String letter = toLetter(totalPercent);
        double gpa = toGpa(letter);

        transcript.append(String.format("TOTAL: %.2f / %.2f\n", earnedTotal, maxTotal));
        transcript.append(String.format("Percentage: %.2f%%\n", totalPercent));
        transcript.append(String.format("Letter Grade: %s\n", letter));
        transcript.append(String.format("GPA: %.2f\n", gpa));

        JOptionPane.showMessageDialog(this,
                new javax.swing.JScrollPane(new javax.swing.JTextArea(transcript.toString(), 20, 50)),
                "Student Transcript",
                JOptionPane.PLAIN_MESSAGE);
    }

    private void loadCourseCombo() {
        cboCourses.removeAllItems();

        for (CourseOffering offering : facultyProfile.getOfferings()) {
            String display = offering.getCourse().getCourseId() + " - "
                    + offering.getCourse().getCourseName()
                    + " (" + offering.getSemester() + ")";
            cboCourses.addItem(display);
        }

        if (cboCourses.getItemCount() > 0) {
            cboCourses.setSelectedIndex(0);
            selectCourseFromCombo();
        }
    }

    private void selectCourseFromCombo() {
        String sel = (String) cboCourses.getSelectedItem();
        studentModel.setRowCount(0);

        if (sel == null || sel.trim().isEmpty()) {
            return;
        }

        int selectedIndex = cboCourses.getSelectedIndex();
        if (selectedIndex < 0 || selectedIndex >= facultyProfile.getOfferings().size()) {
            return;
        }

        selectedCourse = facultyProfile.getOfferings().get(selectedIndex);

        for (Enrollment enrollment : selectedCourse.getEnrollments()) {
            if (enrollment.getStatus().equalsIgnoreCase("Dropped")) {
                continue;
            }

            StudentProfile student = enrollment.getStudent();

            double totalPercent = calculateStudentPercentage(selectedCourse, student);
            String letter = toLetter(totalPercent);
            double gpa = toGpa(letter);

            Object[] row = new Object[6];
            row[0] = student.getPerson().getPersonId();
            row[1] = student.getPerson().getFullName();
            row[2] = student.getPerson().getEmail();
            row[3] = String.format(Locale.US, "%.2f", totalPercent);
            row[4] = letter;
            row[5] = String.format(Locale.US, "%.2f", gpa);

            studentModel.addRow(row);
        }
    }

    private double calculateStudentPercentage(CourseOffering offering, StudentProfile student) {
        ArrayList<Assignment> assignments = offering.getAssignments();

        if (assignments.isEmpty()) {
            String finalGrade = null;
            for (Enrollment e : offering.getEnrollments()) {
                if (e.getStudent().equals(student)) {
                    finalGrade = e.getGrade();
                    break;
                }
            }

            if (finalGrade != null && !finalGrade.isEmpty()) {
                return letterToPercent(finalGrade);
            }
            return 0.0;
        }

        double earnedTotal = 0;
        double maxTotal = 0;

        for (Assignment assignment : assignments) {
            Submission submission = assignment.findSubmissionByStudent(student.getPerson().getPersonId());

            if (submission != null && submission.getStatus().equals("Graded")) {
                earnedTotal += submission.getPointsEarned();
                maxTotal += assignment.getMaxPoints();
            }
        }

        return maxTotal == 0 ? 0 : (earnedTotal / maxTotal) * 100.0;
    }

    private void loadReportSemesterCombo() {
        cboReportSemester.removeAllItems();

        ArrayList<String> semesters = new ArrayList<>();
        for (CourseOffering offering : facultyProfile.getOfferings()) {
            if (!semesters.contains(offering.getSemester())) {
                semesters.add(offering.getSemester());
            }
        }

        for (String sem : semesters) {
            cboReportSemester.addItem(sem);
        }

        if (cboReportSemester.getItemCount() > 0) {
            cboReportSemester.setSelectedIndex(0);
            refreshReportCoursesCombo();
        }

        cboReportSemester.addActionListener(e -> refreshReportCoursesCombo());
    }

    private void refreshReportCoursesCombo() {
        cboReportsCourse.removeAllItems();
        String sem = (String) cboReportSemester.getSelectedItem();

        if (sem == null) {
            return;
        }

        for (CourseOffering offering : facultyProfile.getOfferings()) {
            if (offering.getSemester().equals(sem)) {
                cboReportsCourse.addItem(offering.getCourse().getCourseId() + " - "
                        + offering.getCourse().getCourseName());
            }
        }

        if (cboReportsCourse.getItemCount() > 0) {
            cboReportsCourse.setSelectedIndex(0);
        }
    }

    private void loadTuitionTable() {
        tuitionModel.setRowCount(0);

        double totalBilled = 0, totalPaid = 0, totalDue = 0;

        for (CourseOffering offering : facultyProfile.getOfferings()) {
            for (Enrollment enrollment : offering.getEnrollments()) {
                if (enrollment.getStatus().equalsIgnoreCase("Dropped")) {
                    continue;
                }

                StudentProfile student = enrollment.getStudent();
                int credits = offering.getCourse().getCreditHours();
                double billed = credits * 1000.0;

                double paid = 0;
                double balance = student.getAccount().getOutstandingBalance();
                if (balance >= 0) {
                    paid = billed;
                } else {
                    paid = billed + balance;
                }

                double due = Math.max(0, billed - paid);

                totalBilled += billed;
                totalPaid += paid;
                totalDue += due;

                Object[] row = new Object[6];
                row[0] = student.getPerson().getPersonId();
                row[1] = student.getPerson().getFullName();
                row[2] = offering.getCourse().getCourseId();
                row[3] = currencyFormat.format(billed);
                row[4] = currencyFormat.format(paid);
                row[5] = currencyFormat.format(due);

                tuitionModel.addRow(row);
            }
        }

        Object[] totalRow = {
            "TOTAL", "", "",
            currencyFormat.format(totalBilled),
            currencyFormat.format(totalPaid),
            currencyFormat.format(totalDue)
        };
        tuitionModel.addRow(totalRow);
    }

    private static String toLetter(double pct) {
        if (pct >= 93) {
            return "A";
        }
        if (pct >= 90) {
            return "A-";
        }
        if (pct >= 87) {
            return "B+";
        }
        if (pct >= 83) {
            return "B";
        }
        if (pct >= 80) {
            return "B-";
        }
        if (pct >= 77) {
            return "C+";
        }
        if (pct >= 73) {
            return "C";
        }
        if (pct >= 70) {
            return "C-";
        }
        if (pct >= 60) {
            return "D";
        }
        return "F";
    }

    private static double toGpa(String letter) {
        switch (letter) {
            case "A":
                return 4.0;
            case "A-":
                return 3.7;
            case "B+":
                return 3.3;
            case "B":
                return 3.0;
            case "B-":
                return 2.7;
            case "C+":
                return 2.3;
            case "C":
                return 2.0;
            case "C-":
                return 1.7;
            case "D":
                return 1.0;
            default:
                return 0.0;
        }
    }

    private static double letterToPercent(String letter) {
        switch (letter) {
            case "A":
                return 95;
            case "A-":
                return 91;
            case "B+":
                return 88;
            case "B":
                return 85;
            case "B-":
                return 81;
            case "C+":
                return 78;
            case "C":
                return 75;
            case "C-":
                return 71;
            case "D":
                return 65;
            default:
                return 55;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseEnrollment;
    private javax.swing.JButton btnCourseBack;
    private javax.swing.JButton btnCourseSaveSyllabus;
    private javax.swing.JButton btnOpenEnrollment;
    private javax.swing.JButton btnProfilesBack;
    private javax.swing.JButton btnProfilesEdit;
    private javax.swing.JButton btnProfilesSave;
    private javax.swing.JButton btnReportsBack;
    private javax.swing.JButton btnReportsExport;
    private javax.swing.JButton btnReportsLoad;
    private javax.swing.JButton btnStudentBack;
    private javax.swing.JButton btnStudentGrade;
    private javax.swing.JButton btnStudentTranscript;
    private javax.swing.JButton btnStudentViewRanking;
    private javax.swing.JButton btnTuitionBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboCourses;
    private javax.swing.JComboBox<String> cboReportSemester;
    private javax.swing.JComboBox<String> cboReportsCourse;
    private javax.swing.JPanel jPanelCourses;
    private javax.swing.JPanel jPanelProfiles;
    private javax.swing.JPanel jPanelStudents;
    private javax.swing.JPanel jPanelTuition;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblProfileFacultyID;
    private javax.swing.JLabel lblProfilesDepartment;
    private javax.swing.JLabel lblProfilesEmail;
    private javax.swing.JLabel lblProfilesName;
    private javax.swing.JLabel lblProfilesOfficehrs;
    private javax.swing.JLabel lblProfilesPhone;
    private javax.swing.JLabel lblReportSemester;
    private javax.swing.JLabel lblReportsCourse;
    private javax.swing.JPanel lblReportsSemester;
    private javax.swing.JLabel lblStudentCourse;
    private javax.swing.JTable tblCourses;
    private javax.swing.JTable tblReports;
    private javax.swing.JScrollPane tblTuition;
    private javax.swing.JTextField txtProfileName;
    private javax.swing.JTextField txtProfileOfficeHrs;
    private javax.swing.JTextField txtProfilesDepatment;
    private javax.swing.JTextField txtProfilesEmail;
    private javax.swing.JTextField txtProfilesFacultyID;
    private javax.swing.JTextField txtProfilesPhone;
    // End of variables declaration//GEN-END:variables

}
