/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Business;
import javax.swing.JPanel;
import java.awt.CardLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author anishagaikar
 */
public class FacultyConsole extends javax.swing.JPanel {

    private final Business business;
    private final JPanel cardPanel;

private DefaultTableModel courseModel;
private TableRowSorter<TableModel> sorter;

    /**
     * Creates new form FacultyConsole
     */
    public FacultyConsole(Business business, JPanel CardSequencePanel) {
         this.business = business;
         this.cardPanel = CardSequencePanel;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCourses = new javax.swing.JPanel();
        btnOpenEnrollment = new javax.swing.JButton();
        btnCloseEnrollment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        lblCourse = new javax.swing.JLabel();
        lblCourseTitle = new javax.swing.JLabel();
        lblCourseDescription = new javax.swing.JLabel();
        lblCourseRoom = new javax.swing.JLabel();
        lblCourseTime = new javax.swing.JLabel();
        cboCourse = new javax.swing.JComboBox<>();
        txtCourseTitle = new javax.swing.JTextField();
        txtCourseDescription = new javax.swing.JTextField();
        txtCourseRoom = new javax.swing.JTextField();
        txtCourseTime = new javax.swing.JTextField();
        lblCourseCapacity = new javax.swing.JLabel();
        txtCourseCapacity = new javax.swing.JTextField();
        lblCourseSyllabus = new javax.swing.JLabel();
        txtCourseSyllabus = new javax.swing.JTextField();
        btnCoursesSaveDetails = new javax.swing.JButton();
        btnCourseSaveSyllabus = new javax.swing.JButton();
        btnCourseBack = new javax.swing.JButton();
        jPanelStudents = new javax.swing.JPanel();
        cboCourses = new javax.swing.JComboBox<>();
        lblStudentCourse = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnStudentTranscript = new javax.swing.JButton();
        btnStudentGrade = new javax.swing.JButton();
        btnStudentViewRanking = new javax.swing.JButton();
        btnStudentBack = new javax.swing.JButton();
        jPanelProfiles = new javax.swing.JPanel();
        lblProfileFacultyID = new javax.swing.JLabel();
        lblProfilesName = new javax.swing.JLabel();
        lblProfilesEmail = new javax.swing.JLabel();
        lblProfilesPhone = new javax.swing.JLabel();
        lblProfilesDepartment = new javax.swing.JLabel();
        lblProfilesOfficehrs = new javax.swing.JLabel();
        txtProfilesFacultyID = new javax.swing.JTextField();
        txtProfileName = new javax.swing.JTextField();
        txtProfilesEmail = new javax.swing.JTextField();
        txtProfilesPhone = new javax.swing.JTextField();
        txtProfilesDepatment = new javax.swing.JTextField();
        txtProfileOfficeHrs = new javax.swing.JTextField();
        btnProfilesEdit = new javax.swing.JButton();
        btnProfilesSave = new javax.swing.JButton();
        btnProfilesBack = new javax.swing.JButton();
        lblReportsSemester = new javax.swing.JPanel();
        lblReportSemester = new javax.swing.JLabel();
        lblReportsCourse = new javax.swing.JLabel();
        cboReportSemester = new javax.swing.JComboBox<>();
        cboReportsCourse = new javax.swing.JComboBox<>();
        btnReportsLoad = new javax.swing.JButton();
        btnReportsExport = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();
        btnReportsBack = new javax.swing.JButton();
        jPanelTuition = new javax.swing.JPanel();
        tblTuition = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnTuitionBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jTabbedPane1.setBackground(new java.awt.Color(0, 204, 204));

        jPanelCourses.setBackground(new java.awt.Color(0, 153, 153));

        btnOpenEnrollment.setText("open Enrolment");
        btnOpenEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenEnrollmentActionPerformed(evt);
            }
        });

        btnCloseEnrollment.setText("close Enrollment");

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Title", "Description", "Capacity", "Room", "time"
            }
        ));
        jScrollPane1.setViewportView(tblCourses);

        lblCourse.setText("Course");

        lblCourseTitle.setText("Title");

        lblCourseDescription.setText("Description");

        lblCourseRoom.setText("Room");

        lblCourseTime.setText("Time");

        cboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtCourseTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseTitleActionPerformed(evt);
            }
        });

        lblCourseCapacity.setText("Capacity");

        lblCourseSyllabus.setText("Syllabus");

        btnCoursesSaveDetails.setText("Save Details");

        btnCourseSaveSyllabus.setText("Save Syllabus");

        btnCourseBack.setText("Back");

        javax.swing.GroupLayout jPanelCoursesLayout = new javax.swing.GroupLayout(jPanelCourses);
        jPanelCourses.setLayout(jPanelCoursesLayout);
        jPanelCoursesLayout.setHorizontalGroup(
            jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCoursesLayout.createSequentialGroup()
                .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCoursesLayout.createSequentialGroup()
                        .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCoursesLayout.createSequentialGroup()
                                .addComponent(lblCourseRoom)
                                .addGap(38, 38, 38)
                                .addComponent(txtCourseRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelCoursesLayout.createSequentialGroup()
                                    .addComponent(lblCourseCapacity)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCourseCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelCoursesLayout.createSequentialGroup()
                                    .addComponent(lblCourseDescription)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(78, 78, 78)
                        .addComponent(lblCourseTime)
                        .addGap(18, 18, 18)
                        .addComponent(txtCourseTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCoursesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOpenEnrollment)
                        .addGap(18, 18, 18)
                        .addComponent(btnCloseEnrollment)
                        .addGap(18, 18, 18)
                        .addComponent(btnCoursesSaveDetails)
                        .addGap(18, 18, 18)
                        .addComponent(btnCourseSaveSyllabus))
                    .addGroup(jPanelCoursesLayout.createSequentialGroup()
                        .addComponent(lblCourseSyllabus)
                        .addGap(18, 18, 18)
                        .addComponent(txtCourseSyllabus, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelCoursesLayout.createSequentialGroup()
                            .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCourse)
                                .addComponent(lblCourseTitle))
                            .addGap(30, 30, 30)
                            .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCourseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelCoursesLayout.createSequentialGroup()
                                    .addComponent(cboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCourseBack))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelCoursesLayout.setVerticalGroup(
            jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCoursesLayout.createSequentialGroup()
                .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCoursesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourse)
                            .addComponent(cboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCoursesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCourseBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseTitle)
                    .addComponent(txtCourseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseDescription)
                    .addComponent(txtCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseRoom)
                    .addComponent(lblCourseTime)
                    .addComponent(txtCourseRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseCapacity)
                    .addComponent(txtCourseCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCoursesLayout.createSequentialGroup()
                        .addComponent(lblCourseSyllabus)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCoursesLayout.createSequentialGroup()
                        .addComponent(txtCourseSyllabus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenEnrollment)
                    .addComponent(btnCloseEnrollment)
                    .addComponent(btnCoursesSaveDetails)
                    .addComponent(btnCourseSaveSyllabus))
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Courses", jPanelCourses);

        jPanelStudents.setBackground(new java.awt.Color(0, 153, 153));

        cboCourses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblStudentCourse.setText("Courses");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Email", "Total%", "Letter", "GPA"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnStudentTranscript.setText("Access Transcript");

        btnStudentGrade.setText("Grade Assigning");
        btnStudentGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentGradeActionPerformed(evt);
            }
        });

        btnStudentViewRanking.setText("view Ranking");

        btnStudentBack.setText("Back");

        javax.swing.GroupLayout jPanelStudentsLayout = new javax.swing.GroupLayout(jPanelStudents);
        jPanelStudents.setLayout(jPanelStudentsLayout);
        jPanelStudentsLayout.setHorizontalGroup(
            jPanelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentsLayout.createSequentialGroup()
                .addGroup(jPanelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStudentsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelStudentsLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnStudentTranscript)
                        .addGap(18, 18, 18)
                        .addComponent(btnStudentGrade)
                        .addGap(30, 30, 30)
                        .addComponent(btnStudentViewRanking)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanelStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStudentCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStudentBack)
                .addGap(71, 71, 71))
        );
        jPanelStudentsLayout.setVerticalGroup(
            jPanelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentCourse)
                    .addComponent(btnStudentBack))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentTranscript)
                    .addComponent(btnStudentGrade)
                    .addComponent(btnStudentViewRanking))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("students", jPanelStudents);

        jPanelProfiles.setBackground(new java.awt.Color(0, 153, 153));

        lblProfileFacultyID.setText("Faculty ID");

        lblProfilesName.setText("Name");

        lblProfilesEmail.setText("Email ID");

        lblProfilesPhone.setText("Phone");

        lblProfilesDepartment.setText("Department");

        lblProfilesOfficehrs.setText("Office Hrs");

        txtProfilesDepatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfilesDepatmentActionPerformed(evt);
            }
        });

        btnProfilesEdit.setText("Edit");

        btnProfilesSave.setText("Save");
        btnProfilesSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilesSaveActionPerformed(evt);
            }
        });

        btnProfilesBack.setText("Back");

        javax.swing.GroupLayout jPanelProfilesLayout = new javax.swing.GroupLayout(jPanelProfiles);
        jPanelProfiles.setLayout(jPanelProfilesLayout);
        jPanelProfilesLayout.setHorizontalGroup(
            jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfilesLayout.createSequentialGroup()
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProfilesLayout.createSequentialGroup()
                        .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProfilesLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblProfilesEmail))
                            .addGroup(jPanelProfilesLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblProfileFacultyID)
                                    .addComponent(lblProfilesPhone)
                                    .addComponent(lblProfilesDepartment)
                                    .addComponent(lblProfilesOfficehrs)
                                    .addComponent(lblProfilesName))))
                        .addGap(68, 68, 68)
                        .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProfilesEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProfilesPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProfilesDepatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProfileOfficeHrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelProfilesLayout.createSequentialGroup()
                                .addComponent(txtProfilesFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                                .addComponent(btnProfilesBack))))
                    .addGroup(jPanelProfilesLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnProfilesEdit)
                        .addGap(79, 79, 79)
                        .addComponent(btnProfilesSave)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(56, 56, 56))
        );
        jPanelProfilesLayout.setVerticalGroup(
            jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfilesLayout.createSequentialGroup()
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProfilesLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProfileFacultyID)
                            .addComponent(txtProfilesFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelProfilesLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnProfilesBack)))
                .addGap(18, 18, 18)
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfilesName)
                    .addComponent(txtProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfilesEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfilesEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfilesPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfilesPhone))
                .addGap(16, 16, 16)
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfilesDepatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfilesDepartment))
                .addGap(18, 18, 18)
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfileOfficeHrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfilesOfficehrs))
                .addGap(85, 85, 85)
                .addGroup(jPanelProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfilesEdit)
                    .addComponent(btnProfilesSave))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Profiles", jPanelProfiles);

        lblReportsSemester.setBackground(new java.awt.Color(0, 153, 153));

        lblReportSemester.setText("Semester");

        lblReportsCourse.setText("Course");

        cboReportSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboReportsCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnReportsLoad.setText("Load");
        btnReportsLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsLoadActionPerformed(evt);
            }
        });

        btnReportsExport.setText("Export");
        btnReportsExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsExportActionPerformed(evt);
            }
        });

        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Letter Grade", "Count", "Percentage%"
            }
        ));
        jScrollPane4.setViewportView(tblReports);
        if (tblReports.getColumnModel().getColumnCount() > 0) {
            tblReports.getColumnModel().getColumn(2).setResizable(false);
        }

        btnReportsBack.setText("Back");

        javax.swing.GroupLayout lblReportsSemesterLayout = new javax.swing.GroupLayout(lblReportsSemester);
        lblReportsSemester.setLayout(lblReportsSemesterLayout);
        lblReportsSemesterLayout.setHorizontalGroup(
            lblReportsSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblReportsSemesterLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblReportSemester)
                .addGap(18, 18, 18)
                .addComponent(cboReportSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lblReportsCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboReportsCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportsLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnReportsExport)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblReportsSemesterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lblReportsSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblReportsSemesterLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblReportsSemesterLayout.createSequentialGroup()
                        .addComponent(btnReportsBack)
                        .addGap(82, 82, 82))))
        );
        lblReportsSemesterLayout.setVerticalGroup(
            lblReportsSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblReportsSemesterLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(lblReportsSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReportSemester)
                    .addComponent(lblReportsCourse)
                    .addComponent(cboReportSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboReportsCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportsLoad)
                    .addComponent(btnReportsExport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportsBack)
                .addGap(101, 101, 101))
        );

        jTabbedPane1.addTab("Reports", lblReportsSemester);

        jPanelTuition.setBackground(new java.awt.Color(0, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Billed", "Paid", "Remaining Due"
            }
        ));
        tblTuition.setViewportView(jTable1);

        btnTuitionBack.setText("Back");

        javax.swing.GroupLayout jPanelTuitionLayout = new javax.swing.GroupLayout(jPanelTuition);
        jPanelTuition.setLayout(jPanelTuitionLayout);
        jPanelTuitionLayout.setHorizontalGroup(
            jPanelTuitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTuitionLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanelTuitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTuitionLayout.createSequentialGroup()
                        .addComponent(tblTuition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTuitionLayout.createSequentialGroup()
                        .addComponent(btnTuitionBack)
                        .addGap(63, 63, 63))))
        );
        jPanelTuitionLayout.setVerticalGroup(
            jPanelTuitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTuitionLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(tblTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnTuitionBack)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tuition", jPanelTuition);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentGradeActionPerformed

    private void btnOpenEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenEnrollmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenEnrollmentActionPerformed

    private void txtCourseTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseTitleActionPerformed

    private void txtProfilesDepatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfilesDepatmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfilesDepatmentActionPerformed

    private void btnProfilesSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilesSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfilesSaveActionPerformed

    private void btnReportsLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsLoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportsLoadActionPerformed

    private void btnReportsExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsExportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportsExportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseEnrollment;
    private javax.swing.JButton btnCourseBack;
    private javax.swing.JButton btnCourseSaveSyllabus;
    private javax.swing.JButton btnCoursesSaveDetails;
    private javax.swing.JButton btnOpenEnrollment;
    private javax.swing.JButton btnProfilesBack;
    private javax.swing.JButton btnProfilesEdit;
    private javax.swing.JButton btnProfilesSave;
    private javax.swing.JButton btnReportsBack;
    private javax.swing.JButton btnReportsExport;
    private javax.swing.JButton btnReportsLoad;
    private javax.swing.JButton btnStudentBack;
    private javax.swing.JButton btnStudentGrade;
    private javax.swing.JButton btnStudentTranscript;
    private javax.swing.JButton btnStudentViewRanking;
    private javax.swing.JButton btnTuitionBack;
    private javax.swing.JComboBox<String> cboCourse;
    private javax.swing.JComboBox<String> cboCourses;
    private javax.swing.JComboBox<String> cboReportSemester;
    private javax.swing.JComboBox<String> cboReportsCourse;
    private javax.swing.JPanel jPanelCourses;
    private javax.swing.JPanel jPanelProfiles;
    private javax.swing.JPanel jPanelStudents;
    private javax.swing.JPanel jPanelTuition;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblCourseCapacity;
    private javax.swing.JLabel lblCourseDescription;
    private javax.swing.JLabel lblCourseRoom;
    private javax.swing.JLabel lblCourseSyllabus;
    private javax.swing.JLabel lblCourseTime;
    private javax.swing.JLabel lblCourseTitle;
    private javax.swing.JLabel lblProfileFacultyID;
    private javax.swing.JLabel lblProfilesDepartment;
    private javax.swing.JLabel lblProfilesEmail;
    private javax.swing.JLabel lblProfilesName;
    private javax.swing.JLabel lblProfilesOfficehrs;
    private javax.swing.JLabel lblProfilesPhone;
    private javax.swing.JLabel lblReportSemester;
    private javax.swing.JLabel lblReportsCourse;
    private javax.swing.JPanel lblReportsSemester;
    private javax.swing.JLabel lblStudentCourse;
    private javax.swing.JTable tblCourses;
    private javax.swing.JTable tblReports;
    private javax.swing.JScrollPane tblTuition;
    private javax.swing.JTextField txtCourseCapacity;
    private javax.swing.JTextField txtCourseDescription;
    private javax.swing.JTextField txtCourseRoom;
    private javax.swing.JTextField txtCourseSyllabus;
    private javax.swing.JTextField txtCourseTime;
    private javax.swing.JTextField txtCourseTitle;
    private javax.swing.JTextField txtProfileName;
    private javax.swing.JTextField txtProfileOfficeHrs;
    private javax.swing.JTextField txtProfilesDepatment;
    private javax.swing.JTextField txtProfilesEmail;
    private javax.swing.JTextField txtProfilesFacultyID;
    private javax.swing.JTextField txtProfilesPhone;
    // End of variables declaration//GEN-END:variables
}
